backend/src/main/java/codezap/swagger/SpringDocConfiguration.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateResponse.java
backend/src/main/java/codezap/template/dto/response/CreateTemplateRequest.java
backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
backend/src/main/java/codezap/template/dto/response/FindMemberBySummaryResponse.java
backend/src/main/java/codezap/template/dto/response/FindRepresentativeSnippetResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java

close #20 
1. 스프링독 설정 파일 작성
2. 템플릿 생성, 목록 조회, 단건 조회 API 문서 작성
1. 최소한으로 설명을 작성해놓았으니, 해커톤 종료 후 검토가 필요합니다.

필수 API Swagger 작성

---

.github/workflows/build.yml
backend/src/main/resources/application-local.yml

close #26
- github actions 파일 작성
- github에서 테스트 필요

feat(workflows): actions ci 파이프라인 구성

---

.github/workflows/build.yml
backend/src/main/java/codezap/swagger/SpringDocConfiguration.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateResponse.java
backend/src/main/java/codezap/template/dto/response/CreateTemplateRequest.java
backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
backend/src/main/java/codezap/template/dto/response/FindMemberBySummaryResponse.java
backend/src/main/java/codezap/template/dto/response/FindRepresentativeSnippetResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java
backend/src/main/resources/application-local.yml

⚡️ 관련 이슈
close #26
📍 주요 변경 사항
github actions 파일 작성
🎸 기타
github에서 테스트 필요

CI 파이프라인 구성

---

backend/src/main/java/codezap/extension/repository/ExtensionRepository.java
backend/src/main/java/codezap/language/repository/LanguageRepository.java
backend/src/main/java/codezap/member/domain/Member.java
backend/src/main/java/codezap/member/repository/MemberRepository.java
backend/src/main/java/codezap/snippet/repository/SnippetRepository.java
backend/src/main/java/codezap/template/repository/TemplateRepository.java

close #24
1. 회원, 템플릿, 스니펫, 대표스니펫, 언어, 확장자에 대한 레포지토리를 생성합니다.

모든 레포지토리 생성

---

frontend/package-lock.json
frontend/package.json
frontend/src/App.tsx
frontend/src/index.tsx
frontend/src/pages/Template.tsx
frontend/src/pages/TemplateList.tsx
frontend/src/pages/Templates.tsx
frontend/src/routes/router.tsx
frontend/webpack.config.cjs

close #19
- publicPath: '/' 추가
- historyApiFallback: true
없음

페이지 레이아웃 설정

---

.github/workflows/deploy.yml

close #27 
##📍 주요 변경 사항
github actions 파일 작성
##🎸 기타
github에서 테스트 필요

CD 파이프라인 구축

---

.github/workflows/deploy.yml

#27 
#42 이전 PR
github actions 파일 수정
github에서 테스트 중

[FIX] CD 파이프라인 구축 

---

.github/workflows/deploy.yml

#27 
#42 #43 이전 PR
github actions 파일 수정
github에서 테스트 중

[FIX] CD 파이프라인 구축

---

.github/workflows/deploy.yml

#27 
#42 #43 #44 이전 PR
github actions 파일 수정
github에서 테스트 중

[FIX] CD 파이프라인 구축 4

---

frontend/.eslintrc.cjs
frontend/.prettierrc
frontend/package-lock.json
frontend/package.json

close #52 
1. prettier 설치
2. prettier config 작성
3. eslint-prettier 설정(eslint-config-prettier, eslint-plugin-prettier)

prettier 설정, eslint-prettier 설정

---

backend/build.gradle
backend/src/main/java/codezap/extension/domain/Extension.java
backend/src/main/java/codezap/extension/repository/ExtensionRepository.java
backend/src/main/java/codezap/language/domain/Language.java
backend/src/main/java/codezap/language/repository/LanguageRepository.java
backend/src/main/java/codezap/representative_snippet/domain/RepresentativeSnippet.java
backend/src/main/java/codezap/snippet/domain/Snippet.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/domain/Template.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateResponse.java
backend/src/main/java/codezap/template/service/TemplateService.java

close #38 
1. 코드, 스니펫, 대표 스니펫 생성 로직 구현
2. 🔥 RepresentativeSnippet의 pk를 template_id(fk) -> 새로운 id로 변경
1. lombok annotationProcessor 의존성 추가함

템플릿 생성 API 구현

---

backend/src/main/java/codezap/global/DateTimeFormatConfiguration.java
backend/src/main/java/codezap/global/SpringDocConfiguration.java

close #57 
1. 날짜 시간 형식 지정을 위한 직렬화 설정 파일
+ `ex. 2024-11-26 11:00`
1. 스프링독의 설정 파일의 위치를 `/swagger` ➡️ `/global` 로 이동

날짜 시간 형식 지정을 위한 직렬화 설정

---

frontend/src/components/SelectList/SelectList.tsx
frontend/src/components/SelectList/index.ts
frontend/src/pages/Template.tsx

SelectList 컴포넌트 구현 및 적용

---

backend/src/main/java/codezap/global/WebCorsConfiguration.java

close #65 
1. CORS 설정을 위한 빈 타입을 다른 클래스로 변경하였습니다.
1. 모든 요청에 대해 CORS 를 허용하기 위해 인증 정보 확인 부분을 제거하였습니다.

CORS 설정을 변경

---

README.md

README 팀원 프로필 연결 링크 수정

---

.github/workflows/backend_cd.yml

close #27 
- github actions 파일 작성
- github action의 runner를 이용해 Deploy 작동
- develop/main 브랜치에서 동작
- 추후 develop, main 브랜치가 다르게 동작하도록 변경해야 함

Github Action Runner를 이용한 백엔드 CD 파이프라인 구축

---

.github/workflows/backend_cd.yml

[BE] 배포 확인 작업 명령어 오류 수정

---

.github/workflows/frontend_ci.yml
frontend/package.json
frontend/src/components/TemplateItem/TemplateItem.tsx
frontend/src/mocks/templateList.json
frontend/src/pages/Template.tsx
frontend/src/routes/router.tsx
frontend/src/types/template.ts

react-router-dom의 basename 설정, api filedName 수정

---

backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/repository/SnippetRepository.java
backend/src/main/java/codezap/template/repository/ThumbnailSnippetRepository.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java

템플릿 삭제 기능 구현

---

.github/workflows/backend_cd.yml

close #141 
아키텍처 다운로드 시 레파지토리에 있는 모든 아키텍처 가져온 후, 최근 아키텍처를 알아내는 로직
actions/download-artifact 라이브러리 사용으로 개선

refactor(workflows): cd 아티팩트 다운로드 개선

---

frontend/src/api/templates.ts
frontend/src/hooks/useTemplateDeleteQuery.spec.tsx
frontend/src/hooks/useTemplateDeleteQuery.ts
frontend/src/hooks/useTemplateEditQuery.spec.tsx
frontend/src/hooks/useTemplateEditQuery.ts
frontend/src/mocks/handlers.ts
frontend/src/types/template.ts

close #131 
- 현재 생성, 수정, 삭제 테스트의 경우 단순하게 요청 성공만 테스트하고 있기 때문에 추후 보강이 필요합니다.

템플릿 수정, 삭제 api 요청 기능 추가

---

.github/workflows/frontend_cd.yml

close #152 
- github actions 파일 작성
- build 후 ec2에서 빌드파일 가져와 s3로 전달
캐싱 무효화 자동화 추후 개선

feat(workflows): 배포 파이프라인 구현

---

frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx

close #158
- representative_snippet_ordinal 삭제
- TemplateUploadRequest 타입 지정

템플릿 요청시 사용하지 않는 필드 삭제

---

frontend/src/components/Header/Header.tsx
frontend/src/components/Header/style.ts
frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
frontend/src/pages/TemplateUploadPage/TemplateUploadPage.style.ts
frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx

템플릿 생성페이지, 수정 페이지 디자인 수정

---

frontend/public/index.html

close #172
1. public/index.html 파일에 base URL 추가
[참고 링크](https://github.com/webpack/webpack/issues/2882#issuecomment-280906981)

배포 사이트에서 Unexpected token '<' (at bundle.js:1:1) 에러 해결

---

backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/domain/Category.java
backend/src/main/java/codezap/category/dto/request/CreateCategoryRequest.java
backend/src/main/java/codezap/category/dto/response/FindAllCategoriesResponse.java
backend/src/main/java/codezap/category/dto/response/FindCategoryByIdResponse.java
backend/src/main/java/codezap/category/repository/CategoryRepository.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/main/java/codezap/template/domain/Snippet.java
backend/src/main/java/codezap/template/domain/Tag.java
backend/src/main/java/codezap/template/domain/Template.java
backend/src/main/java/codezap/template/domain/TemplateTag.java
backend/src/main/java/codezap/template/domain/ThumbnailSnippet.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
backend/src/main/java/codezap/template/repository/TagRepository.java
backend/src/main/java/codezap/template/repository/TemplateTagRepository.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java
backend/src/test/resources/clear.sql

1. 템플릿 생성 시 category와 tag 추가
2. 카테고리 생성 및 조회 기능 구현
1. 테스트 코드 동작 안함 -> 추후 수정해야함

템플릿 생성 기능 리팩토링

---

backend/src/main/java/codezap/member/domain/Member.java
backend/src/main/java/codezap/member/repository/MemberRepository.java

1. 다른 도메인에서 사용하기 위해 domain, repository 를 구현하였습니다.
- 다른 도메인 개발을 위한 사전 작업이므로 보시는 대로 최대한 빠른 리뷰 부탁드립니다...!

Member 도메인 생성

---

.github/workflows/backend_cd.yml

close #101
브랜치 구분으로 해결
in, develop 모두 동일한 배포 명령어 사용
브랜치명을 통해 개발 환경 알아 낸 후 배포 명령어 구분
- main - 운영 서버 배포 진행
- develop -  테스트 서버 배포 진행
추후 Environment secrets 사용으로 업데이트 고민 중

[REFACTOR] 무중단 배포 파이프라인 구성

---

backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
backend/src/main/java/codezap/category/domain/Category.java
backend/src/main/java/codezap/category/dto/request/UpdateCategoryRequest.java
backend/src/main/java/codezap/category/dto/response/FindAllCategoriesResponse.java
backend/src/main/java/codezap/category/dto/response/FindCategoryByIdResponse.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/main/java/codezap/template/repository/TemplateRepository.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java

close #196
1. 카테고리 API 문서화
2. 카테고리 수정 / 삭제 기능 구현

카테고리 기능 구현

---

backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java

close #230
1. 템플릿 생성 성공 응답의 설명 수정
2. 템플릿 생성 실패 응답의 `instance` 수정

템플릿 API 문서 수정

---

.github/workflows/backend_cd.yml

close #254 
- CD 배포 환경에 따라서 서버에서 폴더구조를 다르게 구성 
- 이에 따라 actions도 변경
- 브랜치 찾는 명령어 쉘 스크립트로 추출
dev/prod 모두 동일한 폴더에서 action 실행
dev/prod 다른 폴더에서 action 실행
현재 CD 작동이 오류나는 이유는 db가 달라서입니다. member 테이블이 없어서.
수정 필요.

CD jar 파일 다운로드 위치 변경

---

.github/workflows/frontend_cd.yml

close #260 
1. CD 워크플로우에서 .env.production 파일을 생성하고 환경변수를 github secret을 사용해 생성한다.

frontend_cd 빌드 환경에서 환경변수 파일 설정

---

backend/src/main/java/codezap/global/logger/RequestResponseLogger.java

close #277
1. 요청 로깅 시 쿠키 값도 함께 기록

요청 로깅 시 쿠키 헤더 값도 기록

---

backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java
backend/src/main/java/codezap/global/logger/RequestResponseLogger.java

close #302
1. 모든 요청, 응답에 헤더 로깅 추가
1. 모든 헤더 값을 로깅합니다. 불필요한 값들이 많다고 생각합니다. 추후 어떤 헤더만 로깅할 것인지 재논의가 필요할 듯합니다.

모든 요청, 응답에 헤더 로깅

---

.github/workflows/backend_cd.yml

[FIX] 배포 jar 파일 디렉터리 수정

---

frontend/src/api/queryKeys.ts
frontend/src/hooks/authentication/useCheckLoginState.ts
frontend/src/hooks/authentication/useLoginForm.ts
frontend/src/queries/category/useCategoryUpload.ts

카테고리 생성 hotfix

---

backend/src/main/java/codezap/member/service/MemberService.java

close #313 
- 회원가입 시 회원 저장 후 카테고리를 저장합니다.

fix(service): 회원가입 버그 수정

---

frontend/src/api/index.ts
frontend/src/api/templates.ts
frontend/src/hooks/index.ts
frontend/src/hooks/utils/useDebounce.ts
frontend/src/mocks/categoryList.json
frontend/src/mocks/handlers.ts
frontend/src/mocks/templateList.json
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/queries/template/useTemplateListQuery.ts
frontend/src/types/api.ts
frontend/src/types/index.ts

'내 템플릿' 페이지 검색 기능 구현

---

backend/src/main/resources/logback-spring.xml
backend/src/main/resources/logger/logback-spring-dev.xml
backend/src/main/resources/logger/logback-spring-prod.xml

close #320
1. 기존에는 로그 파일의 위치가 상대 경로로 설정되어 있어서, 서버 실행 명령어를 어디에서 선언했는지 위치에 따라 로그 파일의 위치가 변경 되었습니다. 이를 절대 경로로 수정하였습니다.

개발 서버 로그 저장 위치 변경

---

backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java

1. 카테고리 목록 조회시 memberId를 쿼리 파라미터로 넘겨주도록 변경

카테고리 목록 조회 로직 변경

---

backend/src/main/java/codezap/member/controller/MemberController.java
backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
backend/src/main/java/codezap/member/dto/LoginResponse.java
backend/src/main/java/codezap/member/service/MemberService.java

- 로그인 후 사용자 정보를 반환합니다. 
- 사용자 정보를 클라이언트에서 사용할 수 있습니다.

로그인 후 사용자 정보 반환

---

backend/src/main/java/codezap/member/dto/LoginResponse.java

refactor(dto): 응답 형식 변경

---

frontend/src/api/index.ts
frontend/src/api/templates.ts
frontend/src/components/Dropdown/Dropdown.style.ts
frontend/src/components/Dropdown/Dropdown.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/queries/template/useTemplateListQuery.ts
frontend/src/types/api.ts
frontend/src/types/index.ts

close #333
- 정렬 기능 구현
- MSW 핸들러 반영

'내 템플릿' 페이지 정렬 기능

---

backend/build.gradle
backend/src/main/resources/application.yml

close #272
1. actuator 및 micrometer 의존성 추가
2. actuator 관련 yml 파일은 dev 서버에 추가해놓았습니다.

actuator 및 micrometer 의존성 추가

---

backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
backend/src/main/java/codezap/category/repository/CategoryRepository.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/test/java/codezap/category/repository/FakeCategoryRepository.java

카테고리 전체 조회시 id를 기준으로 오름차순으로 정렬되도록 수정

카테고리 전체 조회시 id 오름차순으로 정렬

---

backend/src/main/java/codezap/global/logger/RequestResponseLogger.java

close #362 
1. 응답 요청 로깅에서 /actuator/prometheus 일 경우 제외

응답 요청 로깅에서 /actuator/prometheus 일 경우 제외

---

README.md

close #이슈번호
1. README.md 파일에 위키 링크 추가

README.md 파일에 위키 링크 추가

---

.github/workflows/frontend_cd.yml

sentry auth token 오타 수정

---

frontend/src/api/authentication.ts
frontend/src/api/categories.ts
frontend/src/api/customFetch.ts
frontend/src/api/tags.ts
frontend/src/api/templates.ts
frontend/src/components/Layout/Layout.tsx
frontend/src/hooks/authentication/useSignupForm.ts
frontend/src/hooks/template/useTemplateUpload.ts
frontend/src/queries/tag/useTagListQuery.ts
frontend/src/routes/router.tsx
frontend/src/types/fetch.ts
frontend/src/types/index.ts

#377 
1. customFetch 변경 및 api 레이어 변경
2. ErrorBoundary 적용
3. API URI 변경 (templates, tags)
4. , 오타 수정

ErrorBoundary 적용, Fetch 변경

---

frontend/src/components/Modal/Modal.style.ts
frontend/src/components/Modal/Modal.tsx
frontend/src/components/index.ts
frontend/src/hooks/utils/useModal.ts
frontend/src/pages/TemplatePage/TemplatePage.tsx

모달 컴포넌트 및 삭제 모달 추가

---

frontend/src/contexts/authContext.tsx
frontend/src/queries/authentication/useLoginMutation.ts
frontend/src/queries/authentication/useLogoutMutation.ts
frontend/src/routes/AuthGuard.tsx
frontend/src/routes/GuestGuard.tsx

로그인 상태 유지 기능

---

frontend/src/service/validates.ts

#427 
1. 비밀번호 유효성 검사 변경
2. 비밀번호 유효성 에러메시지 변경
3. 이메일 에러메시지 변경

비밀번호 유효성 검사 변경, 이메일 에러 메시지 변경

---

.github/workflows/backend_cd.yml
.github/workflows/backend_ci.yml
.github/workflows/frontend_cd.yml
.github/workflows/frontend_ci.yml

- CD 실행 브랜치 변경
- self-hosted-runner 사용하도록 변경
- FrontCI, FrontCD 한글로 변경

CD 실행 브랜치 변경 및 self-hosted-runner 사용하도록 변경

---

backend/src/main/java/codezap/member/controller/SpringDocMemberController.java

close #288
1. @ApiErrorResponse가 중복 정의되지 않아, 직접 모든 바디를 작성했던 member controller에 @ApiErrorResponse 적용하였습니다.

member controller에 @ApiErrorResponse 적용

---

backend/src/main/java/codezap/member/controller/MemberController.java
backend/src/main/java/codezap/member/controller/SpringDocMemberController.java
backend/src/main/java/codezap/member/dto/request/UpdateMemberProfileRequest.java
backend/src/main/java/codezap/member/dto/response/FindMemberResponse.java
backend/src/main/java/codezap/member/dto/response/UpdateMemberProfileResponse.java

close #397
1. 회원 정보 수정, 조회 API 문서 작성
1. 응답, 요청, 가능한 에러 응답 중 놓친 부분이 있다면 코멘트 부탁드립니다.

회원 정보 수정, 조회 API 문서 작성

---

frontend/src/api/categories.ts
frontend/src/api/tags.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.spec.tsx
frontend/src/queries/category/useCategoryListQuery.spec.tsx
frontend/src/queries/tag/useTagListQuery.spec.tsx
frontend/src/queries/template/useTemplateListQuery.spec.tsx
frontend/src/routes/GuestGuard.tsx
frontend/src/routes/HomeRouter.tsx
frontend/src/routes/router.tsx

로그인 안한 사용자에게 / 경로가 랜딩페이지로 보이도록 설정

---

frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.style.ts
frontend/src/components/SnippetEditor/SnippetEditor.tsx
frontend/src/components/TemplateEdit/TemplateEdit.tsx

1. 카테고리 글자가 width를 넘길 시, esllipse 처리를 합니다.
2. 기존 Add Snippet, Save, Cancel 를 한글화 합니다.
3. 코드 에디터의 높이를 고정이 아닌 min / max를 정하고 코드에 따라 높이를 변경합니다.

카테고리 글자 esllipse 처리, 영단어 한글화, 코드 에디터 높이 변경

---

.github/workflows/backend_ci.yml
.github/workflows/ci_cd_fail_notification.yml
.github/workflows/frontend_ci.yml
.github/workflows/pr_notification.yml
.github/workflows/review_notification.yml

- CD가 아닌 다른 actions들은 ubuntu-latest 사용으로 변경
- aws codebuild 를 고려
- 혹은 self-hosted-runner 위치 변경 고려

CD가 아닌 다른 actions들은 ubuntu-latest 사용으로 변경

---

frontend/src/components/Header/Header.tsx

#442 
1. Header에 서비스 소개 옵션을 추가한다.
2. 로그인 상태일 때만 내 템플릿 옵션을 활성화한다.

Header에 '서비스 소개'옵션 추가, 로그인 상태에 따른 '내 템플릿' 옵션 활성화

---

.github/workflows/backend_ci.yml

CD가 아닌 다른 actions들은 ubuntu-latest 사용으로 변경하면서 JDK 설정 추가

백엔드 CI JDK 설정 추가

---

.github/workflows/frontend_cd.yml

📍주요 변경 사항
- Beta 서버 환경변수 추가
- Beta 서버 CD 설정

FE CD beta서버 분리

---

backend/src/main/java/codezap/auth/configuration/AuthWebConfiguration.java
backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java

쿠키가 잡히지 않아 제거합니다.
회원만 접근할 수 있는 엔드포인트 검증용 interceptor 제거

회원만 접근할 수 있는 엔드포인트 검증용 interceptor 제거

---

.github/workflows/frontend_ci.yml

- CD가 아닌 다른 actions들은 ubuntu-latest 사용으로 변경
- aws codebuild 를 고려
- 혹은 self-hosted-runner 위치 변경 고려

refactor(workflows):  ubuntu-latest 로 변경

---

frontend/src/components/Header/Header.tsx
frontend/src/contexts/AuthContext.tsx
frontend/src/hooks/category/useCategory.ts
frontend/src/routes/HomeRouter.tsx
frontend/src/routes/RouteGuard.tsx

close #461 
1. HomeRouter에도 로그인 체크 로직 추가
1. RouteGuard의 로직과 비슷하게 변경되었지만 재사용하기엔 약간 달라서, 우선 해결했으나 좋은 방안 있으면 아이디어 주세요..!

'/' 경로에서 새로고침 시, 로그인 해제되는 버그

---

backend/src/main/resources/logback-spring.xml
backend/src/main/resources/logger/logback-spring-prod.xml

#467
현재 배포 작업 초기이므로 info, warn, error를 모두 출력하게끔 설정했습니다. 
배포 작업이 완료된 후 다시 error 단계로 변경될 예정입니다. 
참고하여 리뷰 부탁드려요 😀

운영 환경 로그 설정

---

.github/workflows/backend_cd.yml
.github/workflows/backend_cd_prod.yml

- 브랜치별 runner 결정 시 라벨을 사용하도록 변경

백엔드 cd runner 결정 로직 변경

---

.github/workflows/backend_cd.yml
.github/workflows/backend_cd_prod.yml

runs-on 라벨 사용으로 변경

---

frontend/package-lock.json
frontend/package.json
frontend/public/mockServiceWorker.js
frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx

- #442 
1. codemirror의 langs 익스텐션 설치
2. 확장자명에 따라 문법 하이라이팅 되도록 변경

코드 에디터에서 확장자명에 따라 문법 하이라이팅 기능

---

.github/workflows/ci_cd_fail_notification.yml
.github/workflows/pr_notification.yml
.github/workflows/review_notification.yml

슬랙 알람 워크플로를 기존 self-hosted 로 사용되어 변수를 파일에 저장했었는데 변수 secret에서 가져오도록 변경

fe 슬랙 알람 워크플로 변수 secret에서 가져오도록 변경

---

.github/workflows/backend_cd_prod.yml

- cd-prod deploy시 라벨을 develop에서 production으로 수정

cd-prod deploy 로직 수정

---

.github/workflows/backend_ci.yml

H2 에서 backend CI DB를 mysql로 변경했습니다

backend CI DB를 mysql로 변경

---

.github/workflows/ci_cd_fail_notification.yml
.github/workflows/pr_notification.yml
.github/workflows/review_notification.yml

슬랙 알람 워크플로를 기존 self-hosted 로 사용되어 변수를 파일에 저장했었는데 변수 secret에서 가져오도록 변경

be 슬랙 알람 워크플로 변수 secret에서 가져오도록 변경

---

.github/workflows/frontend_cd.yml

1. frontend_cd 파일 오타 수정 및 rm 명령어 순서 변경

프론트엔드 CD 파일 오타 수정

---

.github/workflows/backend_ci.yml
backend/build.gradle

- h2 의존성 제거
- db yml 가져오는 step 추가

CI 시에 db yml 가져오는 step 추가

---

.github/workflows/backend_ci.yml

working-directory 상대 경로 변경했습니다.

working-directory 상대 경로 변경

---

frontend/src/style/GlobalStyles.tsx

스크롤바 커스텀 디자인

---

frontend/src/components/Input/Input.style.ts
frontend/src/components/LoadingBall/LoadingBall.style.ts
frontend/src/components/LoadingBall/LoadingBall.tsx
frontend/src/components/TemplateEdit/TemplateEdit.tsx
frontend/src/components/index.ts
frontend/src/hooks/utils/index.ts
frontend/src/hooks/utils/useLoaderDelay.ts
frontend/src/service/validates.ts

#512 #510 
1. 카테고리 글자수를 15자로 제한한다.
2. 카테고리 추가 요청 시, 로딩 UI를 추가한다.
3. 카테고리 추가의 안내 메시지를 변경한다

템플릿 업로드 페이지 - 카테고리 글자수 제한, 로딩 UI 추가

---

frontend/src/api/authentication.ts
frontend/src/api/categories.ts
frontend/src/api/templates.ts
frontend/src/components/Header/Header.tsx
frontend/src/pages/LoginPage/LoginPage.tsx
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/queries/authentication/useLoginMutation.ts
frontend/src/queries/authentication/useSignupMutation.ts
frontend/src/routes/endPoints.ts
frontend/src/routes/index.ts
frontend/src/routes/router.tsx

close #542 
1. 로고 경로를 랜딩페이지로 변경합니다.
2. 내 템플릿 버튼은 항상 내 템플릿 페이지를 보여줍니다.
3. 엔드 포인트를 상수화합니다.
1. tag 엔드포인트 상수화가 필요합니다. (/tags 서버 엔드포인트 변경에 따른)

Header 경로 변경, 엔드포인트 상수화

---

frontend/src/components/Header/Header.tsx

1. 비회원이 템플릿 업로드 페이지 이동 시, 페이지가 렌더링되는 버그 임시 해결
임시로 막은 것이라, 리팩토링이 필요합니다.

비회원이 템플릿 업로드 페이지 이동 시, 페이지가 렌더링되는 버그 임시 해결

---

frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx

#510 
카테고리가 없는 사용자가 카테고리를 생성하지 못하는 문제 해결

카테고리가 없는 사용자가 카테고리를 생성하지 못하는 문제 해결

---

backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/service/facade/MemberCategoryApplicationService.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java

카테고리 생성 시 body에 값 추가

---

backend/src/main/java/codezap/tag/service/TemplateTagService.java

tag 수정시 존재하는 태그가 사라지는 오류 수정

---

frontend/src/components/TemplateEdit/TemplateEdit.tsx

- #510 
추후 트러블슈팅 문서화 해두겠습니다
참고 블로그: https://leeseong010.tistory.com/146

카테고리 요청 트리거 onKeyDown 이벤트로 변경

---

frontend/src/components/TemplateCard/TemplateCard.style.ts
frontend/src/components/TemplateCard/TemplateCard.tsx

템플릿 카드에 member 추가

---

backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
backend/src/main/java/codezap/tag/service/TemplateTagService.java
backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java
backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java

태그 중복 제거 문제 해결

---

frontend/src/components/TagInput/TagInput.tsx
frontend/src/hooks/template/useTemplateUpload.ts
frontend/src/hooks/utils/useInputWithValidate.ts

TagInput 첫 글자 삭제되지 않는 bug 수정 및 onBlur 일때 태그 등록되도록 변경

---

.github/workflows/frontend_cd.yml
frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts

#510
1. cd 파일의 ec2 경로 수정
2. 마이 템플릿 페이지 타이틀 정렬 수정

프론트엔드 CD 파일 경로 수정

---

frontend/src/pages/LandingPage/LandingPage.tsx

- #581 
1. 로그인 상태일 때, 랜딩 페이지의 로그인, 회원가입 하러가기 버튼을 숨긴다

로그인 상태일 때, 랜딩 페이지의 로그인, 회원가입 하러가기 버튼 숨기는 기능

---

frontend/src/components/Footer/Footer.style.ts
frontend/src/components/Footer/Footer.tsx
frontend/src/components/Layout/Layout.tsx
frontend/src/components/index.ts

- #581 
1. Footer 컴포넌트를 Layout에 추가합니다.

Layout에 Footer 추가

---

backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java

close #이슈번호
1. 잘못 올렸습니다. 죄송합니다. 근데 저 아님. 몰리임..

Revert "cors를 허용하는 origin 지정"

---

backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java

close #594
cors를 허용하는 origin 을 와일드 카드에서 우리 클라이언트 도메인으로 지정

cors를 허용하는 origin 지정

---

backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java

[Revert "Revert "cors를 허용하는 origin 지정""](https://github.com/woowacourse-teams/2024-code-zap/commit/12c1484a566ebd9c396a5f4cc8f08ad95e526d63)

cors 설정 롤백

---

backend/src/main/java/codezap/auth/service/AuthService.java
backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
backend/src/main/java/codezap/member/service/MemberService.java
backend/src/main/java/codezap/tag/controller/TagController.java

close #594
1. `https://code-zap.com` 설정 추가
+ 기존 허용 도메인에 하위 도메인만 고려하고 `https://code-zap.com`를 고려하지 못했었네요

최상위 도메인 cors 허용

---

frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx

#591
현재 선택된 카테고리가 삭제한 카테고리의 id 배열에 포함된다면, 전체보기로 변경한다.

현재 선택된 카테고리 삭제 시 '전체 보기'로 변경

---

.github/workflows/frontend_cd.yml

#581
- 프론트엔드 CD의 소스코드가 변경 됨(로그 없음)
- 마지막 Merge 시점으로 복구 (#569)

프론트엔드 CD 복구

---

backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java

Reverts woowacourse-teams/2024-code-zap#608

Revert "cors 설정을 스프링 코드에서 제거"

---

backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java

close #620 
TagJpaRepository 관련 테스트 구현
- 메서드 이름 및 쿼리를 직접 작성한 메서드에 대해 테스트를 작성
#624 와 동일한 Flyway 문제 발생

TagJpaRepository 테스트 구현 

---

backend/src/test/java/codezap/tag/repository/TemplateTagJpaRepositoryTest.java

close #620 
1. 메서드 이름 및 쿼리를 직접 작성한 메서드에 대해 테스트를 작성
1. 테스트에 주요하게 사용되는 변수들을 픽스쳐 대신 지역 변수로 변경

TemplateTagRepository 테스트

---

backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java

close https://github.com/woowacourse-teams/2024-code-zap/issues/620
- SourceCodeJpaRepository 관련 테스트 구현
- 쿼리 메서드에 대해 테스트를 작성

SourceCodeJpaRepository 테스트 구현

---

backend/src/test/java/codezap/category/service/facade/MemberCategoryApplicationServiceTest.java

close #645 
MemberCategoryApplicationService Test 구현
#646 에 CI 테스트 문제에 대해 이야기 해보고 싶음
일단 해당 PR은 CI 문제가 발생하지 않도록 세팅해놓음

MemberCategoryApplicationService 테스트

---

backend/src/main/java/codezap/template/domain/Template.java
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java

close #645, #664
예외 케이스까지 한 번에 하려니 너무 오래 걸려서 happy case 테스트만 작성했습니다 😵‍💫😵🫠
또, happy case에서도 sut 실행 결과의 객체 그래프가 너무 깊은 경우 `assertThatCode().doesNotThrowAnyException()`을 사용했습니다. 
점진적으로 케이스를 추가해야할 것 같습니다 😭
테스트코드만 작성하기로 했는데, 프로덕션 코드를 변경하지 않으면 happy case조차 작성할 수 없을 것 같아 변경사항이 있습니다. 
Template.java에 대해 #664 에서 논의를 제안합니다.

TemplateApplicationService 테스트

---

frontend/src/components/Modal/Modal.style.ts
frontend/src/components/NonmemberAlerter/NonmemberAlerter.tsx
frontend/src/components/index.ts
frontend/src/pages/TemplatePage/TemplatePage.tsx

비회원이 좋아요 버튼 클릭 시, 로그인 안내 모달 (비회원 로그인 안내 모달 구현)

---

backend/src/main/java/codezap/likes/controller/LikesController.java
backend/src/main/java/codezap/likes/controller/SpringDocsLikesController.java
backend/src/main/java/codezap/likes/service/LikesService.java
backend/src/test/java/codezap/likes/service/LikesServiceTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java

로그인 정보를 Member 도메인으로 받도록 변경

---

backend/src/test/java/codezap/auth/service/AuthServiceTest.java

close #645
기존에 필요한 테스트 코드가 잘 짜여 있었어요.
Fake DB 를 삭제하는 변경사항밖에 존재하지 않습니다.

AuthService 테스트

---

frontend/src/api/templates.ts
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.style.ts
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
frontend/src/queries/templates/useTemplateExploreQuery.ts

구경가기 페이지에 검색 추가 및 좋아요순 정렬 추가

---

frontend/package.json

close #709 
1. version을 1.1.2로 변경합니다

package.json의 version을 1.1.2로 변경

---

frontend/public/index.html
frontend/src/components/TemplateCard/TemplateCard.tsx

- #695 
1. 초기 페이지 성능 개선을 위해 확실히 일정 시간 안에 네트워크 요청을 보낼 api 서버를 preconnect 합니다.
2. 썸네일 코드에서 Gutter를 제거해 Max depth DOM 경고를 해결합니다.

API 서버 preconnect, 썸네일 코드에서 Gutter 제거

---

frontend/src/components/CategoryGuide/CategoryGuide.tsx

[접근성개선] 카테고리 가이드 숨김 상태일 때 aria-hidden 설정

---

backend/.gitignore
backend/docker/app/application.yml
backend/docker/compose.yml
backend/docker/run.sh

close #640
- 요구사항과 설치 방법을 이슈에서 확인 바랍니다. 
각자 장치에서 #640 의 가이드를 따라 실행 후 리뷰 부탁드립니다.

로컬 환경에서 서버 실행을 위한 도커 컴포즈 스크립트 작성

---

backend/src/main/java/codezap/global/cors/CorsProperties.java
backend/src/main/java/codezap/global/exception/CodeZapException.java
backend/src/main/java/codezap/global/rds/DataSourceRouter.java
backend/src/main/java/codezap/global/serialization/DateTimeFormatConfiguration.java
backend/src/main/java/codezap/global/swagger/AuthOperationCustomizer.java
backend/src/main/java/codezap/global/swagger/error/ApiErrorResponses.java
backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
backend/src/main/java/codezap/global/validation/ValidationGroups.java
backend/src/main/java/codezap/likes/repository/LikesRepository.java
backend/src/main/java/codezap/tag/controller/SpringDocTagController.java
backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/repository/FullTextSearchMySQLDialect.java
backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
backend/src/main/java/codezap/template/repository/SourceCodeRepository.java
backend/src/main/java/codezap/template/repository/TemplateSpecification.java
backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
backend/src/test/java/codezap/auth/manager/CookieCredentialManagerTest.java
backend/src/test/java/codezap/auth/provider/basic/BasicAuthCredentialProviderTest.java
backend/src/test/java/codezap/auth/service/AuthServiceTest.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java

#650
진짜진짜 사소한 코드 컨벤션들 정리했어요 ~
- 클래스 상단 개행 추가
- Nested 테스트 클래스명 첫문자 대문자로
- 사용하지 않는 메서드 삭제
- (이건 다시 원상복구 시킬까 고민중~) lombok.Getter로 코드 개선
레포지토리 단에 다음 메서드들이 테스트 구현되지 않음
- TagRepository - findByNameIn
- TemplateTagRepository - deleteByTemplateIds

전반적으로 자잘한 코드 컨벤션 정리

---

backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java

close #795
> 요청 시 바디가 Json 응답 형식에 맞지 않을 경우, HttpMessageNotReadableException이 발생하며 Failed to read request 라는 예외 메세지를 남기고 있음
400대 에러 중 일부는 ResponseEntityExceptionHandler를 상속하여 핸들링 하고 있는데, 예외 메시지가 더 친절했으면 좋겠다는 문의를 받아 오버라이딩하여 변경함
10/17 13:00

응답 바디 Json 형식 오류 메시지 변경

---

frontend/package.json

version 1.1.4 업데이트

---

backend/src/main/java/codezap/template/controller/TemplateController.java

close #745 
> #808 작업 완료 되어 `@Deprecated` 되었던 API 제거
10/22 03:00

사용되지 않는 로그인용 조회 API 제거

---

backend/src/main/resources/application-db.yml

DB 설정 키를 변경

---

backend/src/main/resources/application.yml

#831
```yml
spring:
profiles:
group:
default: local
dev: db, actautor, swagger, cors
prod: db, actautor, swagger, cors
```
```yml
spring:
profiles:
group:
default: local
dev: db, actuator, swagger, cors
prod: db, actuator, swagger, cors
```
또, [로그백 롤링 정책 변경](https://github.com/woowacourse-teams/2024-code-zap/issues/763)에 따라 promtail이 로그를 읽는 경로도 변경해요. 
```yml
scrape_configs:
static_configs:
labels:
__path__: /mnt/logback/**/*.log
```
```yml
scrape_configs:
static_configs:
labels:
__path__: /mnt/logback/*.log
```
이 문제 때문에 모니터링이 안 돼서, 가능한 빨리 머지하면 좋겠어요~!
10/21 18:00

모니터링에서 스프링 로그 확인 불가한 버그 해결

---

.github/workflows/backend_cd.yml

#833
무중단 배포 구현
다음과 같은 순서로 서버를 실행하여 중단 없이 배포해요. 
1. Nginx가 포워딩하지 않는 서버 컨테이너 확인(이하 idle 서버)
2. Idle 서버 종료
3. 새로운 jar 아티팩트로 idle 서버 실행
4. Idle 서버 health-check
5. Health-check에 성공할 경우 nginx proxy 설정 변경 (idle → active)
유지보수 및 가독성 측면에서 쉘스크립트보다 좋다고 판단해 파이썬으로 작성했어요. 
[배포 스크립트 | Private 저장소](https://github.com/codezap2024/2024-code-zap-private/tree/main/docker/deploy)에서 확인할 수 있어요. 
서버가 비정상적으로 종료되거나, nginx 컨테이너만 종료되는 등 예외상황에 대한 대비가 완전히 되지 않았어요. 
현재는 정상적으로 서버와 nginx가 켜져있을 때에만 문제 없이 무중단 배포 작업을 수행합니다. 
해당 예외 상황들에 대한 보완이 필요해요. 
무중단 배포 로직을 자세히 이해하고 싶다면, 다음 경로의 파일 혹은 디렉토리를 차례대로 살펴보면 돼요. 
1. `/.github/workflows/backend_cd.yml` Github actions 스크립트로 배포 로직이 시작돼요. 
2. [Production Secret | Private 저장소](https://github.com/codezap2024/2024-code-zap-private/blob/production/secret), [Develop Secret | Private …

무중단 배포 파이프라인 구축

---

.gitmodules

- #860
크롬 익스텐션 레포지토리를 코드잽 레포지토리의 서브 모듈로 추가합니다.
ZAPPPPP

크롬 익스텐션 repository 서브모듈 추가

---

.github/workflows/backend_cd.yml
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/domain/Template.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/main/java/codezap/template/service/facade/TemplateOwnershipChecker.java
backend/src/test/java/codezap/template/domain/TemplateTest.java
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java

close #833
PR #857 
무중단 배포 스크립트를 운영 서버에 반영합니다. 
기존에 배포된 서버를 중단하기 위해 수동으로 작업해야 합니다. 
zap

[BE] 무중단 배포 파이프라인 구축

---

frontend/src/components/SourceCode/SourceCode.tsx

- #642 
SourceCode 컴포넌트의 최소 높이 설정합니다.
zappp

SourceCode 컴포넌트의 최소 높이 설정

---

frontend/src/pages/MyLikedTemplatePage/MyLikedTemplatePage.style.ts
frontend/src/pages/MyLikedTemplatePage/MyLikedTemplatePage.tsx
frontend/src/pages/MyTemplatesPage/components/TopBanner/TopBanner.style.ts
frontend/src/pages/MyTemplatesPage/components/TopBanner/TopBanner.tsx
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx

- #642 
- 내템플릿, 구경가기, 좋아요한 템플릿 타이틀 모바일 반응형 적용하였습니다.
10/24

내템플릿, 구경가기, 좋아요한 템플릿 타이틀 모바일 반응형 적용

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/SourceCode/SourceCode.tsx

- #642 
SourceCode 폰트 사이즈 조정
zapppp

SourceCode 폰트 사이즈 조정

---

.github/workflows/backend_cd.yml

https://github.com/woowacourse-teams/2024-code-zap/issues/833
배포 스크립트 실행 전, nginx 설정을 복사하여 항상 동일한 컨테이너(b)가 실행되는 버그를 고쳐요. 
zap

Nginx 설정이 반영되지 않는 버그 수정

---

frontend/src/components/SourceCode/SourceCode.tsx

- #642 
- SourceCode mode에 따라 minHeight 적용 추가
10/24

SourceCode mode에 따라 minHeight 적용 추가

---

frontend/src/api/templates.ts
frontend/src/components/Layout/Layout.tsx
frontend/src/pages/ForbiddenPage/ForbiddenPage.tsx
frontend/src/queries/templates/useTemplateQuery.ts

- #642 
타 유저의 Private 경로 진입 시, Forbidden 페이지 전환합니다.
zappp

타 유저의 Private 경로 진입 시, Forbidden 페이지 전환

---

frontend/jest.config.ts
frontend/package-lock.json
frontend/src/api/ApiClient.ts
frontend/src/api/authentication.ts
frontend/src/api/categories.ts
frontend/src/api/like.ts
frontend/src/api/members.ts
frontend/src/api/tags.ts
frontend/src/api/templates.ts
frontend/src/mocks/fileTransformer.js

- #896 
> Jest 설정 변경을 변경합니다. 정적 파일 transform 설정해주었어요.
(필독!) 
API_URL을 환경변수에서 가져오는 과정에서, new URL 메서드에 빈문자열이 들어가며 에러가 난 것으로 보입니다. 
따라서 환경변수의 기본값으로 더미 url(https://default-url.com)을 우선 넣어주었습니다.
이 과정에서 api 파일마다 API_URL을 각각 바꿔야했습니다.
이후 apiClient로 바꾸면 apiClient에 들어가는 API_URL만 변경하고, msw handler에도 API_URL을 넣으며 
관리 포인트를 하나 혹은 두개로 만들 계획입니당 (지금은 api 파일마다 url을 관리해야함..)
다음 [공식문서](https://jestjs.io/docs/webpack)를 참고했습니다. 
기존의 `moduleNameMapper`로는 해결되지 않았습니다.
11/06 23:59

Jest 설정 변경 - 정적 파일 transform 설정

---

frontend/package.json
frontend/src/pages/LoginPage/LoginPage.tsx
frontend/src/pages/SignupPage/SignupPage.tsx

close #916 
- package.json 버전 업 
- theme 미적용 파일 수정
00/00 00:00

version 1.1.7 변경 및 theme 미적용 파일 수정

---

backend/src/main/resources/logger/console/console-appender.xml

close #913
> 콘솔 로그는 그라파나에서 사용되지 않고, 로컬 환경에서 확인하기 불편하기 때문에 하이라이팅을 추가합
11/15 18:00

콘솔 로그 하이라이팅

---

.github/workflows/backend_cd.yml

서버 마이그레이션하면서 2대 운영하던 서버를 1대로 감축하였습니다.
이에 CD도 prod_a, prod_b 환경에서 돌게했던 코드를 prod_a에서만 동작하도록 수정하였습니다
이전 self-hosted-runner은 삭제했습니다.
> 이 pr이 빨리 머지되서 cd 확인하면 더 좋을 것 같아요 ~
12/02 14:00

서버 scale-in으로 인한 CD 코드 변경

---

backend/.gitignore

#942
QClass는 변경사항에 잡힐 필요가 없어서 gitignore에 추가했어요.
추가로 gitignore에 등록되길 바라는 파일이나 경로가 있다면 알려주세요. 😄
12/04 23:59

QueryDSL QClass 생성 경로를 gitignore에 등록

---

backend/src/main/java/codezap/template/repository/strategy/FullTextSearchSearchStrategy.java
backend/src/main/java/codezap/voc/config/VocClientHttpRequestInterceptor.java
backend/src/main/java/codezap/voc/config/VocConfiguration.java
backend/src/main/java/codezap/voc/config/VocProperties.java
backend/src/main/java/codezap/voc/config/VocResponseErrorHandler.java
backend/src/main/java/codezap/voc/controller/SpringDocVocController.java
backend/src/main/java/codezap/voc/controller/VocController.java
backend/src/main/java/codezap/voc/dto/VocRequest.java
backend/src/main/java/codezap/voc/service/VocService.java
backend/src/main/resources/application-voc.yml
backend/src/main/resources/application.yml
backend/src/test/java/codezap/global/MockMvcTest.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
backend/src/test/java/codezap/voc/config/VocPropertiesTest.java
backend/src/test/java/codezap/voc/controller/VocControllerTest.java
backend/src/test/java/codezap/voc/dto/VocRequestTest.java
backend/src/test/java/codezap/voc/service/VocServiceTest.java

close #962
- 검색시 500 에러가 발생하는 오류 해결
- 문의하기 API 요청 책임을 서버로 변경
12/14 12:00

검색시 500 에러 해결

---

backend/src/main/java/codezap/auth/controller/AuthController.java
backend/src/main/java/codezap/auth/service/AuthService.java
backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/service/SourceCodeService.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java

#992
Request DTO의 변수명을 request로 변경해요. 
```java
void service(CreateTemplateRequest createTemplateRequest) {
}
```
```java
void service(CreateTemplateRequest request) {
}
```
12/30 23:59

Request DTO 변수명을 request로 통일

---

backend/.gitignore

close #1008
1월 3일 회의에서 논의한 것처럼 로컬 환경에서 편리성을 위해 gitignore에 local yml 추가 하였습니다!
01/03 00:00

gitignore에 local yml 추가

---

backend/src/main/resources/application-was.yml

close #1008
톰캣 MBean을 활성화합니다.
> MBean은 Java 객체로, Tomcat의 특정 리소스나 기능을 관리할 수 있게 해주는 인터페이스입니다
> 서버의 상태 모니터링, 설정 변경, 통계 수집 등의 기능을 제공합니다
- 이제 스프링 메트릭 모니터링 대시보드에서 활성 쓰레드 갯수들을 확인할 수 있습니다!
01/04 16:00

톰캣 MBean 활성화

---

backend/src/main/java/codezap/auth/configuration/AuthArgumentResolver.java
backend/src/main/java/codezap/auth/configuration/AuthWebConfiguration.java
backend/src/main/java/codezap/auth/controller/AuthController.java
backend/src/main/java/codezap/auth/controller/SpringDocAuthController.java
backend/src/main/java/codezap/auth/dto/LoginMember.java
backend/src/main/java/codezap/auth/manager/AuthorizationHeaderCredentialManager.java
backend/src/main/java/codezap/auth/manager/CookieCredentialManager.java
backend/src/main/java/codezap/auth/manager/CredentialManager.java
backend/src/main/java/codezap/auth/provider/CredentialProvider.java
backend/src/main/java/codezap/auth/provider/basic/BasicAuthCredentialProvider.java
backend/src/main/java/codezap/auth/service/AuthService.java
backend/src/test/java/codezap/auth/configuration/AuthArgumentResolverTest.java

[FIX] nginx reload 스크립트 고침
