woowacourse-teams/2024-code-zap

backend/src/main/java/codezap/global/domain/BaseTimeEntity.java
backend/src/main/java/codezap/representative_snippet/domain/RepresentativeSnippet.java
backend/src/main/java/codezap/representative_snippet/repository/RepresentativeSnippetRepository.java
backend/src/main/java/codezap/snippet/domain/Snippet.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
backend/src/main/java/codezap/template/dto/response/FindMemberBySummaryResponse.java
backend/src/main/java/codezap/template/dto/response/FindRepresentativeSnippetResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java
backend/src/main/java/codezap/template/service/TemplateService.java

close #21
1. RepresentativeSnippet 엔티티 생성
2. 템플릿 목록 조회 기능 구현 (대표 스니펫 한개의 최대 10줄의 코드와 최종 수정 시간)

템플릿 목록 조회 API 구현

---

backend/src/main/java/codezap/snippet/repository/SnippetRepository.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateBySummaryResponse.java
backend/src/main/java/codezap/template/repository/TemplateRepository.java
backend/src/main/java/codezap/template/service/TemplateService.java

close #37
1. Id 값에 따른 템플릿 상세 조회 기능 구현
1. TemplateRepository의 getById 메서드 이름에 대한 추후 논의가 필요합니다.
2. FindTemplateByIdResponse의 대표 스니펫 순서가 1로 고정되어 있습니다.
+ 추후 대표 스니펫 설정 기능 추가 시 변경이 필요합니다.

템플릿 상세 조회 API 구현

---

.github/workflows/backend_cd.yml
.github/workflows/backend_ci.yml
backend/src/main/resources/application-local.yml

close #82 
1. ci 워크플로에서 실행되는 gradle build 태스크를 test 로 변경
2. 백엔드만 사용하는 ci, cd 파일이므로 backend_ci, backend_cd 로 이름 변경

CI 워크플로에서 태스크를 build에서 test로 변경

---

.github/workflows/frontend_ci.yml

close #90 
1. CI 파일 업로드
- frontend 폴더에서 npm install 후 npm test
1. node 버전을 20으로 맞추었습니다. github actions에서 다음과 같은 warning을 줍니다. 
```
The following actions uses Node.js version which is deprecated and will be forced to run on node20: actions/setup-node@v3. For more info: https://github.blog/changelog/2024-03-07-github-actions-all-actions-will-run-on-node20-instead-of-node16-by-default/
```

프론트엔드 CI 설정 (github actions)

---

backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateSnippetRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
backend/src/main/java/codezap/template/dto/response/FindThumbnailSnippetResponse.java
backend/src/main/resources/application-local.yml

close #108, #111
1. 템플릿 생성, 목록 및 단건 조회 API의 실패 응답 문서화하였습니다.
2. 응답 및 요청 객체에 필드 설명 추가하였습니다.
3. 템플릿 수정, 삭제 API의 문서를 작성했습니다.
1. 수정, 삭제 dto를 생성하였으나 문서화에 대한 내용만 추가하였습니다.
+ 유효성 검증 등 로직을 구현해주세요~! @HoeSeong123 @zangsu 
2. 실패 케이스에 대한 예외 응답을 정하지 않아 문서화되어 있지 않습니다.
+ API 구현 후 예외 응답에 대한 문서화를 추가해주세요~! @HoeSeong123 @zangsu

템플릿 CRUD API의 실패 응답 문서화

---

backend/src/main/java/codezap/global/swagger/error/ApiErrorResponse.java
backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java
backend/src/main/java/codezap/global/swagger/error/ErrorCase.java
backend/src/main/java/codezap/global/swagger/error/ProblemDetailSchema.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java

close #128 
1. 에러 응답을 문서화하기 위한 커스텀 어노테이션 구현 <br> - OperationCustomizer를 통한 실패 응답 추가 자동화
2. SpringDocTemplateController의 Api응답 작성 부분 리팩토링
1. 기존 @ApiReponse를 사용하게 되면 개별 예외 케이스에 대한 응답 예시가 문서화되지 않습니다(이슈 참고 바람) 
따라서 **새로 생성된 커스텀 어노테이션을 사용하여 문서화**해주세요.

실패 케이스 문서화에 사용할 스웨거 커스텀 기능 구현

---

backend/build.gradle

close #202 
1. 롬복 최신 버전을 사용하도록 `build.gradle` 변경
참고자료 : [SOF - How are some gradle dependencies working with no version supplied](https://stackoverflow.com/questions/41676534/how-are-some-gradle-dependencies-working-with-no-version-supplied)

롬복을 최신 버전을 사용하도록 변경

---

frontend/.storybook/preview.tsx
frontend/src/components/Header/Header.tsx
frontend/src/components/Input/Input.stories.tsx
frontend/src/components/Input/Input.tsx
frontend/src/components/Input/style.ts

#203 
1. variation 속성을 반영해 Input 컴포넌트를 기본이 되는 compound 패턴으로 리팩토링 했습니다.
2. Input 스토리북을 variation 중심으로 변경했습니다.
3. 스토리북의 preview의 컴포넌트를 감싸는 배경색을 변경하였습니다.
- 기존 Input 컴포넌트를 사용하던 Header 컴포넌트에서 error가 납니다. 해당 리팩토링은 월하가 담당한다하여 우선 push 합니다.
- 코드 관련 이슈는 코멘트로 적어두겠습니다.

Input 컴포넌트 리팩토링

---

frontend/src/components/Input/Input.style.ts
frontend/src/components/Input/Input.tsx
frontend/src/components/Layout/Layout.style.ts
frontend/src/components/Layout/Layout.tsx
frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
frontend/src/pages/TemplateListPage/TemplateListPage.tsx
frontend/src/pages/TemplatePage/TemplatePage.tsx
frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx

close #233 
1. 레이아웃에 헤더 높이 만큼 padding-top을 일괄적으로 적용한다.
- 현재는 각 페이지마다 적용해야함.
- 적용하는 값도 헤더의 값이 아닌 10rem으로 주고 있었음
2. Input의 style 파일의 rem 값 변경
- 루트 폰트의 0.625 제거로 인한 변경
- 파일 이름을 sytle.ts -> Input.style.ts로 변경

레이아웃에 헤더 높이 만큼 padding-top 적용, Input style rem값 변경

---

backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/dto/request/CreateCategoryRequest.java
backend/src/main/java/codezap/category/dto/request/UpdateCategoryRequest.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
backend/src/main/java/codezap/global/validation/ValidationGroups.java
backend/src/main/java/codezap/global/validation/ValidationSequence.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/domain/Template.java
backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateSnippetRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
backend/src/main/java/codezap/template/dto/response/FindAllSnippetByTemplateResponse.java
backend/src/main/java/codezap/template/dto/response/FindTagByIdResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateByIdResponse.java
backend/src/main/java/codezap/template/dto/response/FindThumbnailSnippetResponse.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/repository/SnippetRepositoryTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java

1. 템플릿 dto에 description 필드 추가
2. Valid 순서 변경
3. 기본 카테고리(`카테고리 없음`) 삭제 요청시 예외처리

제약 조건 추가 및 리팩토링

---

frontend/src/components/Input/Input.stories.tsx
frontend/src/components/Input/Input.style.ts
frontend/src/components/Input/Input.tsx

close #247 
- 기존의 `medium` 사이즈를 `large` 사이즈로 변경

Input 컴포넌트 사이즈 추가

---

backend/src/main/resources/application-local.yml
backend/src/main/resources/application.yml
backend/src/main/resources/logback-spring.xml
backend/src/main/resources/logger/console/console-appender.xml
backend/src/main/resources/logger/console/parameter-appender.xml
backend/src/main/resources/logger/file/error-appender.xml
backend/src/main/resources/logger/file/info-appender.xml
backend/src/main/resources/logger/file/warn-appender.xml
backend/src/main/resources/logger/logback-spring-dev.xml
backend/src/main/resources/logger/logback-spring-local.xml
backend/src/main/resources/logger/logback-spring-prod.xml

close #229 
1. 로그백 설정 및 환경별 구성파일 작성
2. 콘솔 및 파일용 appender 작성
1. 디스커션의 [환경별 로깅 레벨 정하기](https://github.com/woowacourse-teams/2024-code-zap/discussions/200#discussioncomment-10206221)을 참고해주세요.
내일(8월 2일) 오전까지 부탁드립니다.

Logback 구성 및 환경별 설정

---

backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java
backend/src/main/java/codezap/global/logger/MDCFilter.java
backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java
backend/src/main/java/codezap/global/logger/RequestResponseLogger.java

close #207
1. ExceptionHandler 발생 에러 로깅
2. 요청 쓰레드 구분을 위한 MDC 필터 생성
3. 메서드 이름 및 실행 시간 측정을 위한 Aspect 생성
4. 요청 및 응답 로깅용 필터 추가

스프링단 로그 추가

---

.github/workflows/backend_cd.yml
.github/workflows/backend_ci.yml

close #268 
- CI를 self-hosted-runner에서 실행하도록 변경
- CD의 build 실행도 self-hosted-runner에서 실행하도록 변경
- self-hosted-runner에서 jar 파일 생성 후 사용 (아키텍처 이용 안함)
- 캐싱 방법 다른 aciton 사용으로 변경
정확한 문제 파악을 하지 못했다. (어떤 제한이 있는지? 얼마까지만 허용하는지?)
추후 찾아볼 예정. 아는 사람은 알려주세요.

CI/CD build 실행 self-hosted-runner에서 하도록 변경

---

.github/workflows/ci_cd_fail_notification.yml
.github/workflows/pr_notification.yml
.github/workflows/review_notification.yml

close #173
1. ci, cd 실패 시 워크플로 작동 시킨 사람에게 슬랙 알람
2. pr 생성 시 리뷰어에게 알람
3. 리뷰 등록 시 assignee에게 알람
1. 우리 팀이 문서화를 잘해서 디스커션이나 위키 작성 시에도 알람이 가게 할까 생각을 해보았는데, 알람이 너무 많아지는 건가 싶어 고민중입니다.

각종 슬랙 알람을 위한 워크플로 작성

---

backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java

close #287
1. 템플릿 수정 시 새로 생성된 스니펫들이 저장되도록 수정하였습니다.
2. 템플릿 수정 시 올바른 요청이 들어왔는지 확인하는 로직을 수정하였습니다.

실패하는 테스트 코드 수정

---

backend/src/main/java/codezap/global/swagger/error/ApiErrorResponse.java
backend/src/main/java/codezap/global/swagger/error/ApiErrorResponses.java

close #265 
1. 한 메서드에서 `@ApiErrorResponse`가 중복적으로 사용되지 못했는데 `@Repeatable`을 사용하여 중복 가능하게 변경

커스텀한 에러 응답 어노테이션 중복 정의 안되는 이슈 해결

---

backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java

close #282
1. MethodExecutionTimeAspect의 포인트컷 표현식 변경
1. 로거 순환 참조의 문제인 것 같습니다. 포인트컷 표현식 수정했습니다.
+ 두 표현식 차이 공부 필요함

로거 순환 참조로 MethodExecutionTimeAspect 적용되지 않는 문제

---

backend/src/main/resources/logback-spring.xml
backend/src/main/resources/logger/file/error-appender.xml
backend/src/main/resources/logger/file/info-appender.xml
backend/src/main/resources/logger/file/warn-appender.xml
backend/src/main/resources/logger/logback-spring-dev.xml
backend/src/main/resources/logger/logback-spring-prod.xml

close #294
1. dev 서버 로그 안찍히는 문제 해결

dev 서버 로그 안찍히는 문제 해결

---

backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
backend/src/main/java/codezap/category/domain/Category.java
backend/src/main/java/codezap/category/repository/CategoryJpaRepository.java
backend/src/main/java/codezap/category/repository/CategoryRepository.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
backend/src/main/java/codezap/member/repository/MemberRepository.java
backend/src/main/java/codezap/member/service/MemberService.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/domain/Template.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/category/repository/FakeCategoryRepository.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java
backend/src/test/java/codezap/fixture/MemberDtoFixture.java
backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
backend/src/test/java/codezap/member/service/MemberServiceTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/repository/SnippetRepositoryTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java
backend/src/test/resources/clear.sql

close #296
1. 카테고리는 멤버 정보를 가진다.
2. 카테고리 조회, 수정, 삭제는 카테고리를 생성한 유저만 할 수 있다.
3. 템플릿 멤버 정보를 가진다.
4. 템플릿 조회, 수정, 삭제는 템플릿를 생성한 유저만 할 수 있다.
5. 템플릿 생성 시 카테고리 할당은 본인이 생성한 카테고리만 사용할 수 있다.
6. 템플릿 삭제 시 없는 템플릿을 삭제할 경우 예외 처리 되도록 변경하였습니다.
1. 템플릿 삭제 시 권한이 있는지 확인해야 하기 때문.

템플릿, 카테고리 CRUD에 멤버 정보 추가

---

backend/src/main/resources/logback-spring.xml

close #294
1. logback springProfile을 그룹이 아닌 각각으로 설정
> logback 설정이 실행중인 스프링 프로파일에 맞게 각 환경별 로그 구성 되도록 해놓았었습니다. 따라서 dev 환경에서는 dev 프로파일을 기준으로 로그 구성을 실행 시킴. 그런데 active 프로파일 dev-1로 바꾸니까 됩니다.
spring.config.location가 위치를 지정하는 거지 active 프로파일이 아니였습니다.
1.

logback springProfile 재지정

---

backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java

예외처리 문서화 추가

---

.github/workflows/frontend_cd.yml
.gitignore
frontend/src/components/Header/Header.tsx
frontend/src/hooks/authentication/useCheckLoginState.ts
frontend/src/hooks/authentication/useLoginForm.ts
frontend/src/pages/LoginPage/LoginPage.tsx
frontend/src/pages/SignupPage/SignupPage.tsx
frontend/src/routes/AuthGuard.tsx
frontend/src/routes/GuestGuard.tsx
frontend/src/routes/router.tsx

close #324 
1. 로그인 상태에 따라 Routes 접근을 제어합니다.
- 로그인 상태라면 login, signup 경로 접근 불가
- 아니라면 템플릿 조회 경로 접근 불가
2. frontend_cd 에 Sentry 환경변수 추가
3. 로그인, 회원가입 안내메시지의 스타일 변경
- '계정이 없으신가요', '이미 계정이 있으신가요'의 align, size, gap 변경
- 현재 클라이언트의 로그인 상태는 로그인, 로그아웃 요청의 결과로만 변경됩니다.
- 어느 시점에서 서버에 해당 유저에 대한 로그인 상태 체크 요청을 보내고 로그인 상태를 업데이트 시킬지 결정해야합니다.

로그인 상태에 따른 Routes 보호,  frontend_cd 업데이트, 로그인/회원가입 안내메시지 스타일 변경

---

backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java

1. 카테고리 목록 조회시 meberId를 쿼리 파라미터로 받도록 변경

카테고리 목록 조회 로직 변경

---

frontend/src/api/authentication.ts
frontend/src/api/categories.ts
frontend/src/api/templates.ts
frontend/src/contexts/authContext.tsx
frontend/src/hooks/authentication/useLoginForm.ts
frontend/src/queries/authentication/useLoginMutation.ts
frontend/src/queries/category/useCategoryListQuery.ts
frontend/src/queries/template/useTemplateListQuery.ts
frontend/src/types/api.ts
frontend/src/types/authentication.ts

#241 #315  #330 
1. 로그인 요청에 대한 response 추가
2. useAuth 전역 context에 로그인 후 받아온 멤버 정보인 memberId, username 관리
3. 템플릿 목록 조회 및 카테고리 목록 조회 요청의 Params에 memberId 추가
1. sort 기능 구현 PR과 conflict가 나서 resolve 했습니다. 제일 마지막 merge 커밋 한번 봐주시면 좋을거 같아요. (`keyword=''` 이런거 지운게 아니라 중복되어 있는 것 지웠어요!)

auth 전역 상태에 멤버 정보 추가, 템플릿 목록 조회 및 카테고리 목록 조회 요청의 Params에 memberId 추가

---

backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java

템플릿 반환 값에 생성 시간 포함하도록 변경

---

backend/src/main/java/codezap/template/repository/TemplateTagRepository.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java

템플릿 태그 검색 시 모든 태그가 포함된 템플릿만 검색되도록 수정
- 'Login', 'JWT' 두개의 태그를 선택해서 검색했을 시, 'Login'과 'JWT' 태그 둘 중 하나라도 포함된 경우 검색된다.
- 'Login', 'JWT' 두개의 태그를 선택해서 검색했을 시, 'Login'과 'JWT' 태그 둘 다 포함된 경우만 검색된다.

템플릿 태그 검색 시 모든 태그가 포함된 템플릿만 검색되도록 수정

---

.github/workflows/frontend_cd.yml

폴더를 생성하는 로직이 실행될 때 이미 폴더가 존재해서 문제 발생
폴더 생성 전에 폴더 삭제 로직 추가

CD 수정, 아티팩터 다운로드 폴더 삭제 및 생성

---

frontend/src/components/Layout/Layout.tsx
frontend/src/pages/NotFoundPage/NotFoundPage.tsx
frontend/src/pages/index.ts
frontend/src/routes/router.tsx

ErrorBoundary에 NotFound 페이지 적용

---

backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java

close #393
1. GlobalExceptionHandler를 Spring이 제공하는 에러 핸들링에 대한 base class로 ResponseEntityExceptionHandler를 상속받도록 수정하였습니다.
ResponseEntityExceptionHandler 는 Spring MVC에서 발생시키는 예외를 처리하는 핸들러입니다.
NoResourceFoundException 부터 MethodArgumentNotValidException 등등 예외를 처리하는 로직이 포함되어 있습니다.
[ResponseEntityExceptionHandler](https://docs.spring.io/spring-framework/docs/current/javadoc-api/org/springframework/web/servlet/mvc/method/annotation/ResponseEntityExceptionHandler.html)
+) MethodArgumentNotValid가 ResponseEntityExceptionHandler에서 처리되고 있어 재정의하도록 파라미터와 메서드명 수정하였습니다.
---
내일 1시 전까지 리뷰 완료 부탁드립니다.

GlobalExceptionHandler를 ResponseEntityExceptionHandler를 상속

---

backend/src/main/java/codezap/global/swagger/error/ApiErrorResponsesCustomizer.java

close #270 
1. 이전 pr을 통해 하나의 api에 대해 여러 실패 예시를 정의할 수 있었으나,  하나의 status에 대해 예외 상황이 여러개일 경우 가장 먼저 정의된 하나만 적용되는 에러를 해결하였습니다.
2. ApiResponses의 addApiResponse 는 map을 사용하기 때문에 기존 "클라이언트 오류"와 같은 description을 key로 저장하게 되면 다른 에러가 덮어씌워지는 문제가 발생했습니다. 
따라서 description에 상태 코드를 추가하여 구분하였습니다.

하나의 status에 대해 예외 상황이 여러개일 경우, 문서가 덮어씌워지는 에러 해결

---

backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/dto/request/CreateSnippetRequest.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateSnippetRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
backend/src/main/java/codezap/template/dto/response/FindThumbnailSnippetResponse.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/service/TagSearchTest.java
backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java

close #395
- 템플릿 선택 삭제 API 문서
- 썸네일 조회 기능 API 문서
- 템플릿 에러 케이스 추가 구현
- 추후 API docs에 맞게 에러 메시지 수정 예정
- 현재는 swagger 실행 시, 에러 케이스 출력 안된다. 해당 문제에 대한 PR 존재(#418)

템플릿 선택 삭제 및 조회 시 썸네일 스니펫 추가한 API 문서 작성

---

frontend/src/api/customFetch.ts
frontend/src/components/Layout/Layout.tsx
frontend/src/hooks/authentication/useSignupForm.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/NotFoundPage/NotFoundPage.tsx
frontend/src/queries/authentication/index.ts
frontend/src/queries/authentication/useSignupMutation.ts
frontend/src/queries/template/useTemplateListQuery.ts

#439 
1. ErrorBoundary에 query reset과 key를 추가합니다.
- 에러 바운더리에서 홈으로 가기 버튼이나 네비게이션을 클릭해도 url만 바뀔 뿐, 에러 바운더리가 언마운트되지 않는 현상을 해결합니다.
2. templateList 쿼리의 throwOnError 옵션을 true로 하여 에러바운더리에서 캐치하도록 변경합니다.
3. 회원가입의 api 함수를 tanstack-query의 mutation을 이용하도록 합니다.

에러 바운더리에 query reset과 key 추가

---

frontend/public/index.html
frontend/src/style/GlobalStyles.tsx

#442 
1. 브라우저에서 font의 경로를 찾지 못해 error, warn 이 나는 현상을 해결합니다.

font 404 에러 해결

---

backend/src/main/java/codezap/auth/configuration/AuthorizationInterceptor.java
backend/src/main/java/codezap/auth/controller/AuthController.java
backend/src/main/java/codezap/category/domain/Category.java
backend/src/main/java/codezap/member/domain/Member.java
backend/src/main/java/codezap/template/domain/SourceCode.java
backend/src/main/java/codezap/template/domain/Tag.java
backend/src/main/java/codezap/template/domain/Template.java
backend/src/main/java/codezap/template/domain/TemplateTag.java
backend/src/main/java/codezap/template/domain/Thumbnail.java
backend/src/main/java/codezap/template/dto/request/validation/SourceCodesCountValidator.java
backend/src/main/java/codezap/template/dto/request/validation/SourceCodesOrdinalValidator.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/test/java/codezap/auth/provider/basic/BasicAuthDecoderTest.java
backend/src/test/java/codezap/auth/service/AuthServiceTest.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java
backend/src/test/java/codezap/fixture/MemberDtoFixture.java
backend/src/test/java/codezap/member/controller/MemberControllerTest.java
backend/src/test/java/codezap/member/domain/MemberTest.java
backend/src/test/java/codezap/member/fixture/MemberFixture.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
backend/src/test/java/codezap/template/service/TagSearchTest.java
backend/src/test/java/codezap/template/service/TemplateServiceSearchTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java

- 충돌한 테스트 코드 해결
- equals & hashcode 재정의
- @EqualsAndHashCode 사용 시 프록시 객체 비교 안 됨
- 재정의 방법
- getClass() vs instanceOf 사용 -> getClass() 사용 (intanceOf는 상속한 객체 비교도 true 라서 안됨)
- getter로 id 가져오기 (프록시 객체일 경우 값이 없을 수 있기 때문에 getter를 이용해 실제 값 가져오기)

충돌한 테스트 코드 해결 및 equals 재정의

---

backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
backend/src/main/java/codezap/category/dto/response/CreateCategoryResponse.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java

카테고리 생성 시 생성된 카테고리 값 반환

---

backend/build.gradle
backend/src/main/java/codezap/global/flyway/FlywayRepairConfiguration.java
backend/src/main/resources/db/migration/V1__init.sql

close #423
1. flyway 의존성 추가
1. 스키마 체크를 부탁드립니당 (휴먼 에러 발생 가능 폴폴)
2. 앞으로 db 스키마 마이그레이션 시 flyway 문법에 맞춰 파일을 작성해야 합니다
3. ddl-auto 옵션도 none 또는 validate로 변경해야 합니다.
4. FlywayMigrationStrategy 재정의를 통해 repair 후 migration 작업을 수행하도록 변경
인프라 담당분 application-db.yml에 해당 부분 추가가 필요합니다. 
```
spring:
flyway:
enabled: true
baseline-on-migrate: true
locations: classpath:db/migration
```
각 옵션의 의미는 다음과 같습니다.
+ spring.flyway.enabled=true
+ Spring Boot 애플리케이션에서 Flyway를 활성화합니다.
+ 애플리케이션 시작 시 Flyway가 자동으로 마이그레이션을 실행합니다.
+ spring.flyway.baseline-on-migrate=true
+ 비어있지 않은 데이터베이스에 대해 자동으로 baseline을 설정합니다.
+ 기존 데이터베이스에 Flyway를 처음 적용할 때 발생할 수 있는 문제를 예방합니다.
+ spring.flyway.locations=classpath:db/migration
+ 마이그레이션 스크립트 파일의 위치를 지정합니다.
+ 지정된 경로에서 마이그레이션 스크립트를 찾아 실행합니다.
다른 참고사항은 아래 글을 참고하여 구현해주세요.
[달록의 데이터베이스 마이그레이션을 위한 …

flyway 설정 추가

---

backend/src/main/java/codezap/global/logger/MDCFilter.java
backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
backend/src/main/resources/logger/file/error-appender.xml
backend/src/main/resources/logger/file/info-appender.xml
backend/src/main/resources/logger/file/warn-appender.xml

close #420 
- Spring Filter의 순서 설정에 관련된 문제이므로 개발서버뿐 아니라 운영서버에도 적용되는 내용입니다. 
1. 로그에 `correlationId`를 부여하는 MDC 필터의 순서를 1로 설정합니다. 
2. HTTP 요청과 응답 로그를 출력하는 `RequestResponseLogger`의 순서를 2로 설정합니다. 
- 추후 Filter 작업 시 순서를 고려해야 합니다. 
[요청, 응답 로그에 correlationId 를 추가하자!](https://github.com/woowacourse-teams/2024-code-zap/wiki/%EC%9A%94%EC%B2%AD%2C-%EC%9D%91%EB%8B%B5-%EB%A1%9C%EA%B7%B8%EC%97%90-correlationId-%EB%A5%BC-%EC%B6%94%EA%B0%80%ED%95%98%EC%9E%90%21)

HTTP 요청과 응답의 Thread UUID가 출력되지 않는 버그 해결

---

frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
frontend/src/components/Modal/Modal.style.ts
frontend/src/components/Modal/Modal.tsx

Modal 컴포넌트 완성

---

.github/workflows/frontend_cd.yml

1. CD 파일의 오타를 수정하고 rm 명령어의 순서를 바꿉니다.

프론트엔드 CD 파일 오타 수정

---

backend/src/main/resources/application-local.yml

close #495
1. 페이지네이션 시에 페이지의 시작 인덱스를 1로 지정해주는 옵션 문법이 틀려서 제거합니다.
인프라팀
🔥 application-db.yml에 아래 꼭 추가해주세요!!!!!!!! 🔥
```
spring:
data.web.pageable.one-indexed-parameters: true
```
🔥 자기 로컬 application-db.yml에도 꼭 추가해주세요!!!!!!!! 🔥

페이지네이션 시에 페이지의 시작 인덱스를 1로 지정해주는 옵션 제거

---

backend/src/test/java/codezap/global/DatabaseCleaner.java
backend/src/test/java/codezap/global/DatabaseIsolation.java
backend/src/test/java/codezap/global/repository/JpaRepositoryTest.java

close #469
1. 테스트 시 각 메서드 격리를 위한 DatabaseCleaner 클래스 생성
- AbstractTestExecutionListener의 beforeTestMethod를 재정의히여 매 테스트 메소드 실행 전 데이터베이스를 클린업하는 로직이 수행되도록 함
- 클린업하는 로직
- 모든 테이블을 비우고 외래 키 제약 조건을 일시적으로 비활성화하여 **TRUNCATE 작업 수행**합니당
2. `@DatabaseIsolation` 생성
- 1번에서 만든 DatabaseCleaner를 테스트 실행 리스너로 추가하고, 기존 리스너들과 병합
- 쉽게 말해 `@DatabaseIsolation` 어노테이션을 부착하게 되면 매 테스트 시 DatabaseCleaner가 동작합니다.
3. DataJpaTest에서 공통적으로 사용될 어노테이션들을 묶은 베이스 어노테이션 `@JpaRepositoryTest` 생성
- @DataJpaTest, @DatabaseIsolation 등 레포지토리 단위 테스트 시 필요한 여러 어노테이션을 조합
- JPA Auditing 기능 사용을 위한 JPA Auditing 설정 파일 import
1. 테스트 시 데이터베이스 격리를 위해 여러 방법 중 AbstractTestExecutionListener 재정의를 선택한 이유는 아래 블로그 글을 참고하시면 좋을 것 같습니다
- [TestExecutionListener을 활용한 테스트 격리](https://velog.io/@appti/TestExecutionListener%EC%9D%84-%ED%99%9C%EC%9A%A9%ED%95%9C-% …

테스트 시 DB 격리 및 레포지토리 테스트를 위한 베이스 어노테이션 생성

---

frontend/src/api/tags.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx

#510
- 🐛 API 요청 엔드포인트 변경 (/templates/tags > /tags)
- 🐛 '내 템플릿' 페이지에서 태그가 0개일 때, '0'이 렌더링 되는 문제

태그 API 요청 엔드포인트 변경 / 태그가 0개 일 때, 태그박스 자리에 0이 렌더링 되는 문제 해결

---

backend/src/main/java/codezap/template/repository/TemplateJpaRepository.java
backend/src/main/java/codezap/template/repository/TemplateRepository.java
backend/src/main/java/codezap/template/repository/TemplateSpecification.java
backend/src/test/java/codezap/template/repository/FakeTemplateRepository.java
backend/src/test/java/codezap/template/repository/TemplateRepositoryFindAllTest.java

close #495
- 동적 쿼리 생성을 위한 Specification 구현체 생성
- Specification 실행을 위해 TemplateJpaRepository가 JpaSpecificationExecutor를 상속받도록 변경
- Specification를 인자로 전달하는 템플릿 조회 쿼리 메서드 생성
- 동적 쿼리 적용 테스트 작성
- 기존 분기처리된 조회 쿼리문들을 대처하는 로직은 다음 pr에 올라갑니당
- FakeTemplateRepository에서 null 반환하는 이유
- Specification을 어떻게 할 수가 없음...........아는 사람 알려주세요............ Fake 슬프다.........
> 문서화 나중에 해놓을게요 ㅠㅠㅠㅠㅠㅠ
일단은 [JPA의 동적 쿼리](https://tecoble.techcourse.co.kr/post/2022-10-11-jpa-dynamic-query/) 글 먼저 봐줘요.....
+) 코멘트에 설명 추가했습니다

템플릿 조회에서 동적 쿼리 생성을 위한 Specification 구현

---

frontend/src/components/CategoryEditModal/CategoryEditModal.style.ts
frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
frontend/src/components/CategoryFilterMenu/CategoryFilterMenu.tsx
frontend/src/components/Modal/Modal.style.ts
frontend/src/hooks/category/useCategoryNameValidation.ts
frontend/src/mocks/handlers.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx

close #510
- 🚀 메뉴 > 카테고리 버튼 클릭 시, 스크롤 이벤트 제거
- 🚀 모달 > 카테고리 아이템의 Hover/Error/Edit 상태 스타일링
- 🐛 모달 > 임시 카테고리 아이디 부여 방식 수정
- 🚀 모달 > 카테고리 이름 에러 시, 카테고리 추가 버튼 비활성화 스타일링
- 🚀 모달 > 카테고리 추가 시, 기본 카테고리명 제거 및 Placeholder 추가

카테고리 편집 메뉴 및 모달 리팩토링 (2차 UT 및 QA 반영)

---

backend/src/main/java/codezap/auth/provider/basic/BasicAuthCredentialProvider.java
backend/src/main/java/codezap/auth/service/AuthService.java
backend/src/main/java/codezap/category/controller/CategoryController.java
backend/src/main/java/codezap/category/controller/SpringDocCategoryController.java
backend/src/main/java/codezap/category/service/facade/MemberCategoryApplicationService.java
backend/src/main/java/codezap/member/controller/MemberController.java
backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
backend/src/main/java/codezap/member/repository/MemberRepository.java
backend/src/main/java/codezap/member/service/MemberService.java
backend/src/main/java/codezap/tag/controller/SpringDocTagController.java
backend/src/main/java/codezap/tag/controller/TagController.java
backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/dto/response/FindAllTemplateItemResponse.java
backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
backend/src/main/java/codezap/template/dto/response/FindTemplateResponse.java
backend/src/main/java/codezap/template/repository/TemplateSpecification.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/main/java/codezap/template/service/facade/MemberTemplateApplicationService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/member/controller/MemberControllerTest.java
backend/src/test/java/codezap/member/repository/FakeMemberRepository.java
backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java
backend/src/test/java/codezap/member/service/MemberServiceTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/repository/TemplateRepositoryFindAllTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java

close #495
1. 비회원 조회 가능하도록 태그, 카테고리, 템플릿 조회 시 MemberDto 제거
2. 권한 확인 로직 및 관련 테스트 제거
+) FakeRepository 사용으로 인해 테스트 거짓 양성이 계속해서 발생하고 있습니다. 이에 대해 논의가 필요할 것 같아요.

비회원 조회 가능하도록 태그, 카테고리, 템플릿 조회 시 MemberDto 제거

---

backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java

close #551
1. 템플릿 삭제 시 템플릿 연관관계의 친구들을 먼저 삭제하고 템플릿을 마지막에 삭제해야 하는데, 순서가 변경되어 있었습니다.

템플릿 삭제 시 다른 리소스 삭제 순서 변경

---

backend/src/main/java/codezap/template/service/SourceCodeService.java

수정 시 썸네일 삭제 안되는 문제 해결
- 원인 : thumbnail 비교 시 thumbnail.sourceCode.id 비교가 아닌 thumbnail.id 비교

fix(service): 썸네일 소스코드 삭제 안되는 문제 해결

---

backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java

close #594
1. cors를 허용하는 origin 을 와일드 카드에서 우리 클라이언트 도메인으로 지정

cors를 허용하는 origin 지정

---

frontend/src/api/customFetch.ts
frontend/src/api/templates.ts
frontend/src/components/CategoryEditModal/CategoryEditModal.tsx
frontend/src/components/TemplateEdit/TemplateEdit.tsx
frontend/src/hooks/template/useTemplateUpload.ts

- #581 
- 템플릿 생성 실패할 경우, 라우터 이동 없이 생성 화면단 유지하기
- 템플릿 생성 실패할 경우, 토스트로 실패하였다고 알림하기
- 템플릿 생성 description input placeholder 문구 변경
https://github.com/user-attachments/assets/1baacec4-eddf-4033-985c-d8621c46962e
- 현재 템플릿 생성, 수정 요청에서 응답으로 올 수 있는 에러 코드
- 401
- 400
- 404
- 여기서 401 은 유저 인증에 대한 부분이므로 전체에서 핸들링 되어야 한다고 판단 => 나머지 400, 404에 대해서만 에러처리하였습니다.
- 에러핸들링 및 customFetch 의 리팩토링 필요합니다.

템플릿 생성 실패한 경우, 토스트로 알림 및 라우터 유지하도록 변경

---

frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
frontend/src/service/index.ts
frontend/src/service/validates.ts
frontend/src/utils/getByteSize.ts
frontend/src/utils/index.ts

#581
- Validation 코드 분리
- 최대 글자수에서 한글(3Byte)를 입력하여 글자수를 초과하면 3회 시도부터 에러 발생
- 에디터의 글자를 통째로 덮어씌우기 때문에, 커서의 위치가 에디터의 처음으로 초기화

파일명, 소스코드 길이 제한

---

frontend/src/pages/LoginPage/LoginPage.tsx
frontend/src/pages/SignupPage/SignupPage.tsx
frontend/src/service/validates.ts

- close #602 
1. 아이디, 비밀번호 글자수를 각각 255자, 16자의 상한선 제한을 둔다
2. 아이디 에러 메시지를 변경한다
3. 비밀번호 에러 메시지를 변경한다
4. 로그인, 회원가입 페이지에서 아이디 라는 인풋 라벨을 아이디(닉네임)으로 변경한다

아이디, 비밀번호 글자수 상한선 제한

---

backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java

#615 
크롬 extension cors 허용을 위해 `"chrome-extension://bmlonhfgleihfabinjbhgefojkfpmlaf"` 해당 접근도 허용허도록 변경

크롬 extension cors 설정 추가

---

backend/src/main/java/codezap/global/cors/CorsProperties.java
backend/src/main/java/codezap/global/cors/WebCorsConfiguration.java
backend/src/main/resources/application-local.yml
backend/src/test/java/codezap/global/MockMvcTest.java
backend/src/test/java/codezap/global/cors/CorsPropertiesTest.java
backend/src/test/resources/application-local.yml

close #615
1.  @ConfigurationProperties 로 값 yml 에서 읽어오도록 변경
1. dev, prod yml 파일 수정

cors allow origin 을 yml에서 읽어오도록 변경

---

backend/src/main/java/codezap/member/repository/MemberJpaRepository.java
backend/src/test/java/codezap/member/repository/MemberJpaRepositoryTest.java

close #620 
MemberJpaRepository 관련 테스트 구현
- 메서드 이름 및 쿼리를 직접 작성한 메서드에 대해 테스트를 작성
- V1__init.sql 실행으로 문제 발생 -> 테이블이 이미 존재해서 에러
- Flyway는 각 마이그레이션 파일에 고유한 버전을 부여하며, 이 버전이 flyway_schema_history 테이블에 기록된 경우 동일한 버전의 스크립트는 재실행되지 않는다. 
-  flyway_schema_history 확인하면 version 1 등록되어 있음
- ![image](https://github.com/user-attachments/assets/dc0f60c1-e608-41d6-b5b9-51c13768831d)
@zeus6768 가 도와줌
결론 : applicatoin-db.yml 파일을 test 패키지에 구현하지 않았음. 
줄줄 이야기 해봐요 :
test 패키지에 yml 파일이 하나라도 구현했다면 사용하는 모든 yml 파일을 새롭게 구현해야 했음.
하지만 그걸 모르고 applicatoin-db.yml 파일을 test 패키지에 구현하지 않았음. 
application-db.yml 파일을 test 패키지에 추가하고 나니 해결
1차 결론 후 또 안됨, create-drop 이 아닌 validate인 경우 안됨
초켬제 머리 합친 결과 : 몰리가 구현해준 test annotaiton이랑 충돌하나로 결론
1. 몰리가 구현해준 어노테이션 실행 시키면 모든 테이블 드랍하는 거와 flyway 충돌
2. 테스트에서는 creat-drop 으로 하기로 함 ~

MemberJpaRepository 테스트 구현

---

backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java

#620
- `ThumbnailRepository` 객체는 `sut`로 변수명을 선언했습니다. SUT는 'System Under Test'의 약자로, 테스트의 대상이 되는 객체를 의미합니다. 
- 테스트에서 선언된 변수명이 많을 때 테스트 대상을 빠르게 찾기 위해 일관된 변수명을 사용합니다. 
- 출처: [단위 테스트](https://m.yes24.com/Goods/Detail/104084175) 56p, 87p.
- 기존에 Thumbnail 도메인에 대한 레포 테스트가 존재하지 않았습니다. 
- 이에 구현합니다.

ThumbnailRepositoryTest 구현

---

backend/src/test/java/codezap/category/repository/CategoryRepositoryTest.java

#620
#627 에 해당 변수명을 사용한 이유를 명시했습니다. 
- 기존에 Category 도메인에 대한 레포 테스트가 존재하지 않았습니다. 
- 이에 구현합니다.

CategoryRepositoryTest 구현

---

.github/workflows/frontend_playwright.yml
frontend/.gitignore
frontend/e2eTests/example.spec.ts
frontend/jest.config.ts
frontend/package-lock.json
frontend/package.json
frontend/playwright.config.ts

- close #636 
1. playwright 초기 설정을 한다.

프론트엔드 E2E 테스트 - playwright 설정

---

backend/src/test/java/codezap/fixture/SourceCodeFixture.java
backend/src/test/java/codezap/global/ServiceTest.java
backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java

close #645
1. 생성, 삭제, 조회, 수정 등에 대한 테스트 작성
1. 테스트를 하면서 로직이 이상한 경우 또는 검증이 되어있지 않는 경우가 다수 있었습니다. 해당 pr은 테스트에 대한 것이기 때문에 main 로직의 수정이 필요한 경우에 대해서는 우선 작성하고 @Disable 처리를 해놓았습니다.
이슈 #650 에 여러가지 문제 사항들을 정리를 해두었으니 확인 부탁드립니다.
2. 또 현재 소스 코드 수정 로직이 복잡합니다. (매우)
열심히 작성했지만 놓친 엣지 케이스나 잘못 작성된 부분이 있다면 알려주세요~

SourceCodeService 테스트 추가

---

backend/src/test/java/codezap/global/cors/CorsPropertiesTest.java
backend/src/test/java/codezap/global/repository/JpaRepositoryTest.java
backend/src/test/java/codezap/member/service/MemberServiceTest.java
backend/src/test/resources/application-local.yml

close #645 
MemberService Test 보충 및 MemberServiceTest 실제 DB 사용으로 변경
Repository 단에서 나는 에러 처리도 서비스 테스트에서 확인하는게 맞을지 의문이 들긴합니다.
일단 추가하긴했는데 함께 고민하면 좋을 것 같아요 여러분들의 의견은 어떤가요?
> **요약 정리**
> `@SpringBootTest` 환경 설정 MOCK으로 하고 `@AutoConfigureTestDatabase` 설정 안하면 문제 해결
> BUT, 이게 맞을까 싶음
몰리 PR을 보니 CI 문제가 발생 안함.
그래서 뭐가 다른지 확인해보니 몰리는 기본 설정인 MOCK 사용하고, `@AutoConfigureTestDatabase` 설정이 없음
그래서 바꿔보니 해결 되네..? 왜 RANDOM_PORT 에서 문제가 발생할까요? 실제 환경이랑 동일하게 테스트하고 싶은 저희 욕구에 맞추려면 RANDOM_PORT를 사용하는게 좋을 것같은데 문제가 발생해서 애매하네요.. ㅜ
~~실제 DB를 사용하려면 해당 어노테이션 추가해야하지 않나요? 그런데 추가하면 에러 발생함~~
~~제가 해당 어노테이션에 대해 다음과 같이 이해했는데 잘못된 정보가 있거나 해당 어노테이션이 없어도 DB를 잘 사용한다는 게 보장된다면 지우겠습니다~~
~~- 없을 때: Spring Boot는 테스트 실행 시 기본적으로 임베디드 데이터베이스를 사용하며, 빠르게 실행되지만 실제 DB 환경과 차이가 있을 수 있음.~~
~~- 있을 때: 실제 데이터베이스를 그대로 사용하여 운영 환경과 더 유사한 테스트가 가능하지만, 속도가 느릴 수 …

Member Service 테스트 

---

backend/src/test/java/codezap/global/ServiceTest.java
backend/src/test/java/codezap/template/service/facade/CategoryTemplateApplicationServiceTest.java

close #645
1. CategoryTemplateApplicationService 테스트를 작성하였습니다.
2. ServiceTest가 SourceCodeService pr 과 중복됩니다. pr 머지 시 충돌이 발생할 수 있으나 필요하다고 생각하여 추가했습니다~
1. 리팩토링이 필요한 부분이 있는 듯합니다. 의견을 이슈에 작성해놓았으니 https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2355273823 참고해주세요.
2. 테스트를 하기 위해 해당 서비스의 역할을 생각해보았습니다. 관련 의문과 제안을 이슈 https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2356004453 에 작성해두었으니 참고해주세요.
3. https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2355576069 짱수와 동일한 프록시 객체 접근 문제가 발생합니다~ @Transactional 어노테이션을 통해 트랜잭션을 생성하는 방식으로 처리했습니다.

CategoryTemplateApplicationTest 추가

---

backend/src/test/java/codezap/category/service/facade/MemberCategoryTemplateApplicationServiceTest.java

close #645 
MemberCategoryTemplateApplicationService Test 구현
#646  에 CI 테스트 문제에 대해 이야기 해보고 싶음
일단 해당 PR은 CI 문제가 발생하지 않도록 세팅해놓음

MemberCategoryTemplateApplicationService 테스트

---

backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java

close #645 
TemplateService 테스트 작성
켬미와 동일하게 flyway 설정 때문에 테스트 코드가 자꾸 실패하는 문제가 발생했었습니다.
이에 테스트 코드에서 사용하는 `application-db.yml`에 다음과 같은 설정을 추가해주었습니다.
```
flyway:
enabled: false
```
- TemplateService의 경우 아래 코드와 같이 TemplateRepository의 반환값을 그대로 리턴하는 메소드들이 몇 개 있습니다.
```java
public Template getById(Long id) {
return templateRepository.fetchById(id);
}
public List<Template> getByMemberId(Long memberId) {
return templateRepository.findByMemberId(memberId);
}
public Page<Template> findAll(
Long memberId, String keyword, Long categoryId, List<Long> tagIds, Pageable pageable
) {
return templateRepository.findAll(
new TemplateSpecification(memberId, keyword, categoryId, tagIds), pageable);
}
```
- 이런 경우 RepositoryTest와 중복되는 테스트들이 몇 개 생겨나는데 이런 경우에도 ServiceTest를 작성해야 하는지 의문입니다.
- 우선 저는 중복되더라도 테스트 코드를 …

TemplateServiceTest 추가

---

backend/src/test/java/codezap/category/service/CategoryTemplateServiceTest.java

close #645
- 실제 db 사용하도록 변경
- 테스트 코드의 오류 수정
- `CategoryTemplateService` 의 존재에 대해 이야기를 해 보면 좋을 것 같아요.
- 우선 이슈에 글을 달아둘게요.

CategoryTemplateService 테스트 

---

backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java

close #645 
ThumbnailSerivce 테스트 작성
- 사용하지 않는 메서드 삭제
- https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2357303578
- 중복 검사 로직
- https://github.com/woowacourse-teams/2024-code-zap/issues/650#issuecomment-2357302571

썸네일 서비스 테스트코드 작성

---

backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java

close #645 
CategoryService Test 구현
지금 테스트 코드 하나가 터질거에요.
이유는 comment 로 남겨 두었으니 확인 바랍니다.

CategoryService 테스트 

---

backend/src/main/java/codezap/category/domain/Category.java
backend/src/test/java/codezap/template/service/facade/MemberTemplateApplicationServiceTest.java

close #645, #664
#665 와 같은 이유로 happy case 테스트만 작성했습니다. 
Category 변경사항에 대해 #664 에서 논의를 제안합니다.

MemberTemplateApplicationService 테스트

---

backend/src/main/java/codezap/template/dto/request/CreateSourceCodeRequest.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateSourceCodeRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java

close #667
- `@Validated` 으로 검증 로직을 작동시키기 위해 dto 필드에 group 설정 추가
아직 컨트롤러 테스트 보완이 안되있어서 고민하다가 그래도 현재 fix하는 로직이 잘 작동하는지 확인하기 위해 dto 검증 테스트 코드 추가했습니다.
primitive type 은 null 일 수 없으니 NotNull 체크가 없어도 될 것 같은데 어떻게 생각하시나요?
> 이 외에도 없는지 추후 컨트롤러 테스트 보완하면서 확인하면 좋을 것 같다

group 설정 추가로 @Validated 검증 로직 보완

---

backend/src/main/java/codezap/likes/controller/LikesController.java

이전의 좋아요 기능 응답 코드는 다음과 같았습니다.
- 좋아요 성공 : 200
- 좋아요 취소 성공 : 204
200 응답은 좋아요를 하나의 동작으로 본 경우, 204 응답은 좋아요를 하나의 자원으로 본 경우라고 생각해요.
좋아요를 하나의 동작으로 본다면 200 / 200 응답이, 하나의 자원으로 본다면 201 / 204 응답이 적절할 것 같습니다.
이에 대한 논의는 아마 각자의 선호도가 달라 통일시키기 어려울 것으로 보입니다. 
또한, 옳고 그름의 문제가 아닌지라 어떤 선택이든 납득이 가능하기도 해요.
그래서 헤인의 "그렇다면 예외 처리 하기 편하게 200 으로 던져줘도 될까?" 라는 요청을 고려해 200 / 200 응답으로 수정합니다.

좋아요 기능의 응답 코드를 통일

---

backend/src/main/java/codezap/template/controller/TemplateController.java

close #690
```
spring:
data.web.pageable.one-indexed-parameters: true
```
사용 시 기본 Controller 단에 도착하기 전에 위 설정이 적용되어 page 값이 1 적게 옵니다.
내부 레포지토리 로직에서는 여전히 0-based 인덱스를 사용합니다.
따라서 Controller에서 기본 값을 1이 아닌 0으로 재설정해줍니다.

목록 조회 페이지 기본 값을 0으로 변경

---

backend/src/main/java/codezap/global/rds/DataSourceConfig.java
backend/src/main/java/codezap/global/rds/DataSourceRouter.java
backend/src/main/java/codezap/likes/service/LikesService.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/main/java/codezap/template/service/ThumbnailService.java
backend/src/main/resources/logger/logback-spring-prod.xml

close #699 
1. 운영 환경의 데이터베이스를 RDS로 변경합니다.
2. `@Transational(readOnly=true)`를 설정하면 Reader 인스턴스를 사용하게 되고, `@Transactional`을 사용하거나 아예 사용하지 않으면 Writer 인스턴스를 사용합니다.
3. 해당 설정은 운영환경에만 적용됩니다.

RDS reader writer 적용

---

frontend/webpack.common.js

- #695 
1. 캐시 관리
- 빌드시 cache busting 적용
- 빌드 파일에 버전 정보와 content hash를 붙입니다. content hash는 파일 내용에 따라 hash가 결정되며 변경사항이 없을 시 동일한 hash 값이 붙습니다.
- hash에 더불어 version도 붙이는 것이 명시적이라고 생각했습니다. 해당 부분 관련해서 논의할 내용이 있다면 알려주세요.
1. [hash 관련 참고 자료](https://velog.io/@jiseong/Webpack-hash-chunkhash-%EA%B7%B8%EB%A6%AC%EA%B3%A0-contenthash-%EC%BA%90%EC%8B%B1%EC%A0%84%EB%9E%B5)

build시 정적 리소스에 cache busting 기법 적용

---

frontend/src/components/NoSearchResults/NoSearchResults.style.ts
frontend/src/components/NoSearchResults/NoSearchResults.tsx
frontend/src/components/index.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx

NoSearchResults 생성 및 적용

---

frontend/src/api/templates.ts
frontend/src/components/Footer/Footer.tsx
frontend/src/components/LoadingFallback/LoadingFallback.style.ts
frontend/src/components/LoadingFallback/LoadingFallback.tsx
frontend/src/components/index.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/pages/MyTemplatesPage/components/CategoryFilterMenu/CategoryFilterMenu.stories.tsx
frontend/src/pages/MyTemplatesPage/components/CategoryFilterMenu/CategoryFilterMenu.tsx
frontend/src/pages/MyTemplatesPage/components/TagFilterMenu/TagFilterMenu.stories.tsx
frontend/src/pages/MyTemplatesPage/components/TagFilterMenu/TagFilterMenu.tsx
frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.stories.tsx
frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.tsx
frontend/src/pages/TemplatePage/TemplatePage.tsx
frontend/src/queries/templates/index.ts
frontend/src/queries/templates/useTemplateCategoryTagQueries.ts
frontend/src/routes/router.tsx

- #695
- MyTemplatePage 초기 랜더링 Layoutshift 개선 
**- GLS 0.837 => 0.012 로 개선**
|Before|After|
|---|---|
|<img width="570" alt="image" src="https://github.com/user-attachments/assets/557b0b27-751c-418f-abad-863bd28f151c">|![image](https://github.com/user-attachments/assets/cbbf86db-a517-4298-ae34-413cfd01c5da)
- `useTemplateCategoryTagQueries` 에서 3개의 요청이 모두 성공할 때 까지 기다림
- 기존에는 키워드 없어도 '' 으로 보내줬으나, 백엔드 측에서 사용하지 않는 params 보내지 않도록 변경 요청하여 반영함.
- templates, categories, tags => templateList, categoryList, tagList로 이름 변경
- 컨벤션으로 복수형보다는 List 와 같은 명시적인 단어로 표현하기로 했기 때문.
=> 추후 컴포넌트 계층 분리를 다시 한 후 서스펜스를 각각 감싸보면 어떨까 싶습니다.

MyTemplatePage 초기 랜더링 Layoutshift 개선

---

backend/src/main/java/codezap/tag/domain/Tag.java
backend/src/main/java/codezap/tag/repository/TagRepository.java
backend/src/main/java/codezap/tag/service/TagService.java
backend/src/main/java/codezap/template/domain/TemplateTag.java
backend/src/main/resources/db/migration/V5__create_idx_tag_name.sql
backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
backend/src/test/java/codezap/template/repository/FakeTagRepository.java

close #673
- [쿼리 성능 개선 ‐ 템플릿 생성](https://github.com/woowacourse-teams/2024-code-zap/wiki/%EC%BF%BC%EB%A6%AC-%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0-%E2%80%90-%ED%85%9C%ED%94%8C%EB%A6%BF-%EC%83%9D%EC%84%B1)
- [쿼리 성능 개선 ‐ 템플릿 수정](https://github.com/woowacourse-teams/2024-code-zap/wiki/%EC%BF%BC%EB%A6%AC-%EC%84%B1%EB%8A%A5-%EA%B0%9C%EC%84%A0-%E2%80%90-%ED%85%9C%ED%94%8C%EB%A6%BF-%EC%88%98%EC%A0%95)

템플릿 생성, 수정 쿼리 성능 개선

---

backend/src/main/java/codezap/template/repository/FullTextSearchMySQLDialect.java
backend/src/main/java/codezap/template/repository/TemplateSpecification.java
backend/src/main/resources/db/migration/V6__add_full_text_index.sql
backend/src/test/java/codezap/global/DatabaseCleaner.java
backend/src/test/java/codezap/template/repository/TemplateJpaRepositoryTest.java
backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java
backend/src/test/resources/search.sql

close #673
JPA는 전문 검색 인덱스를 지원하지 않습니다.
따라서 직접 JPQL 또는 커스텀 MySQLDialect을 통해 전문 검색 인덱스를 타도록 설정해주어야 합니다.
그런데 현재 검색 쿼리가 동적으로 생성되어 Specification 을 사용하고 있습니다.
Specification과 JPQL은 동시 사용이 불가능하여 커스텀 MySQLDialect 방식으로 구현하였습니다.
모든 환경의 yml 파일에 아래의 내용이 추가되어야 합니다.
커스텀 MySQLDialect을 등록이 필요합니다.
```yml
jpa:
properties:
hibernate:
dialect: codezap.template.repository.FullTextSearchMySQLDialect
```

전문 검색 인덱스 적용

---

backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java

close #548
1. 스웨거 서버에 개발 (`dev.code-zap.com`) 서버 추가하였습니다.

Swagger 개발 서버 IP 추가

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Toast/Toast.tsx
frontend/src/routes/router.tsx
frontend/webpack.common.js
frontend/webpack.dev.js
frontend/webpack.prod.js

- #695 
- `router` 파일의 페이지 컴포넌트를 `Suspense`, `Lazy`를 사용하여 CodeSplitting 구현
- 각 번들 파일에 대해 개별적 chunks로 분리 (content hash)
- TreeShaking이 동작하지 않고 여전히 모든 컴포넌트를 한 번에 가져오는 문제
- 원인 : Barrel 방식에서 Webpack은 SideEffects 가능성이 있다고 판단
- 해결방안 : `Package.json`에 명시적으로 SideEffects 가능성을 배제
<br>
- `compression-webpack-plugin`을 사용하여 britli 압축
<br>
<br>
|Before|After|
|---|---|
|![image](https://github.com/user-attachments/assets/1aacdb2c-d35a-4d75-b8a1-4c4932513010)|![image](https://github.com/user-attachments/assets/020a038f-6f45-4139-b1a8-f17771114344)|
|![image](https://github.com/user-attachments/assets/3e873359-07da-46a1-a2f7-e82a41747851)|![image](https://github.com/user-attachments/assets/fcd1c281-f733-4849-ab59-5b1c54f6b076)|

Bundle 사이즈 최적화

---

backend/src/main/java/codezap/category/dto/request/CreateCategoryRequest.java
backend/src/main/java/codezap/global/validation/ByteLength.java
backend/src/main/java/codezap/global/validation/GroupedByteLengthValidator.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
backend/src/test/java/codezap/category/controller/CategoryControllerTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java

close #512
1. 태그 및 카테고리 생성 시 글자수 검증
2. 기존 `@ByteLength`에 List<String> 에 대해 글자 수 검증을 하는 GroupedByteLengthValidator 객체를 추가하였습니다.
+ `@ByteLength` 사용 시 타입에 맞는 validator 클래스가 선택되어 검증합니다.

태그 및 카테고리 생성 시 글자수 검증

---

frontend/src/components/Input/Input.style.ts
frontend/src/components/Input/Input.tsx
frontend/src/components/SourceCodeViewer/SourceCodeViewer.tsx
frontend/src/pages/LoginPage/LoginPage.tsx

- #722 
- placeholder를 추가하고, 해당 placeholder 스타일을 투명하게 주어 보이지 않게 처리했습니다.
- button 태그를 추가하고 해당 버튼에 aria-label 달아주었습니다.
- isSourceCodeOpen 여부에 따라 aria-label 읽도록 설정해주었습니다.
- 상세페이지 구현 결과
https://github.com/user-attachments/assets/b5898253-7197-4f75-9fc0-c3ef51beb0fd
- 로그인페이지 구현 결과
https://github.com/user-attachments/assets/03c67da0-4676-4181-b318-1ea46c64bd2d
(컴퓨터에서 녹화했는데 왜인지 소리는 녹음이 안되네요😂)

[접근성 개선] 로그인 input 및 상세페이지 소스코드 접기 버튼 접근성 개선

---

backend/src/main/java/codezap/likes/domain/Likes.java
backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
backend/src/main/java/codezap/likes/repository/LikesRepository.java
backend/src/main/java/codezap/likes/service/LikesService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
backend/src/test/java/codezap/likes/repository/LikesJpaRepositoryTest.java
backend/src/test/java/codezap/likes/service/LikesServiceTest.java
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java

close #734
템플릿 삭제 시 템플릿에 연관된 좋아요 삭제 로직 추가
꽤 급한 bug라고 생각해요~ 이거 merge되면 dev에서 확인하고 main 올려요 ~
템플릿과 소스코드 양방향 연관관계를 제거한 후, Cascade 설정으로 제거하는 방안 어떨까요?
cascade는 쉽게 설명해서 cascade 설정을 하면 템플릿 삭제 시 자동으로 템플릿과 연관된 데이터가 삭제되는 설정을 의미한다.
> [JPA Cascade는 무엇이고 언제 사용해야 할까?](https://tecoble.techcourse.co.kr/post/2023-08-14-JPA-Cascade/)
cascade는 ‘게시물’과 ‘댓글’의 관계처럼 부모 - 자식 구조가 명확하다면 Cascade를 사용하는 것은 괜찮은 선택이다. 
우리 서비스에서 이에 해당하는 관계는 다음과 같다. 하지만 하나의 자식에 여러 부모가 대응되는 경우(‘수강 중인 수업’과 ‘학생’의 관계 등)에는 사용하지 않는 것이 좋다. 
우리 서비스에서 템플릿 삭제 시 삭제해야 하는 모든 관계는 부모 - 자식 구조가 명확하다고 생각한다.
- template - like
- template - sourcecode
- sourcecode- thumbnail
- template - tag
template와 sourcecode가 양방향 매핑이고, 아직 잘 알진 못하니 더 찾아보려고
+의논이 필요할까해서~ 
> 양방향 매핑은 cascade 사용이 위험하다.
> 그 이유는 위에 참고 자료 확인!
> 간단하게 말하자면 양방향 매핑이면, sourcecode 삭제 시 템플릿 삭제될 수도 있음

좋아요한 템플릿 삭제 시 좋아요 테이블 삭제 구현

---

backend/src/main/java/codezap/tag/repository/TagJpaRepository.java
backend/src/main/java/codezap/tag/repository/TagRepository.java
backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
backend/src/main/java/codezap/tag/service/TagService.java
backend/src/test/java/codezap/tag/repository/TagJpaRepositoryTest.java
backend/src/test/java/codezap/template/repository/FakeTagRepository.java

close #758
related #757
요구사항은 다음과 같습니다.
- 대소문자 구분
- `tag.name` 칼럼에 설정된 인덱스 효율 유지
- 단건 조회, 다건 조회 모두 적용
```java
Optional<Tag> findByName(String name);
@Query("select t.name from Tag t where t.name in :names")
List<String> findNameByNamesIn(@Param("names") List<String> names);
```
```java
@Query(value = "SELECT * FROM tag WHERE tag.name = BINARY :name", nativeQuery = true)
Optional<Tag> findByName(@Param("name") String name);
@Query(value = "SELECT * FROM tag WHERE tag.name COLLATE utf8mb4_bin IN :names", nativeQuery = true)
List<Tag> findAllByNames(@Param("names") List<String> names);
```
만약 다음과 같이 사용할 경우, name 칼럼의 인덱스를 사용하지 않고 full scan 합니다.
```java
@Query(value = "SELECT * FROM tag WHERE BINARY tag.name = :name", nativeQuery = true)
Optional<Tag> findByName(@Param("name") String name); …
```

태그 이름으로 태그 조회 시 대소문자를 구분하지 않아 태그가 중복으로 반환되는 버그 수정

---

frontend/src/components/Header/Header.tsx
frontend/src/components/NonmemberAlerter/NonmemberAlerter.tsx
frontend/src/hooks/index.ts
frontend/src/hooks/useCustomNavigate.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/pages/NotFoundPage/NotFoundPage.tsx
frontend/src/pages/SignupPage/hooks/useSignupForm.ts
frontend/src/pages/TemplatePage/hooks/useTemplate.ts
frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
frontend/src/queries/authentication/useLoginMutation.ts
frontend/src/queries/authentication/useSignupMutation.ts
frontend/src/routes/RouteGuard.tsx

- #575 
- 위 이슈의 19번: 히스토리 다 쌓을 필요 없음. 업로드 7번 누르면 뒤로가기 7번 해야함

같은 경로로 이동시 히스토리 쌓이지 않도록 변경

---

frontend/package.json
frontend/src/components/Header/Header.style.ts
frontend/src/components/Header/Header.tsx
frontend/src/pages/LoginPage/LoginPage.tsx

- #722 
1. 헤더의 햄버거 메뉴 태그를 button으로 변경 후 aria-label='메뉴' 추가
2. 헤더의 새 템플릿 버튼 포커스 시, '템플릿 작성 페이지로 이동됩니다' aria-description 추가
3. 로그인 페이지의 아이디, 비밀번호 input에 요구사항을 스크린 리더가 읽도록 aria-label로 추가
1. 한가지 고려해볼 사항이 있는데, 코멘트로 남길게요.

[접근성 개선] - 상단 Header, 로그인 Input

---

backend/src/main/java/codezap/global/exception/GlobalExceptionHandler.java

#521
- 스프링에서 반환하는 response에는 detail 정보가 없는 문제 있었음
- 스웨거에서 직렬화 하는 코드에서 문제 발생 -> problemDetail에 새로운 값으로 LocalDateTime이 추가되는데 이는 직렬화가 안됨
- 커스텀하기 전 전달 객체가 이미 ProblemDetail이어서 전달 객체에 커스텀 properties만 추가
- problemDetail에 LocalDateTime을 toString()해서 문자열로 변환

[FIX] 에러코드 detail 정보 없는 경우 수정 및 스웨거 수정

---

backend/src/main/resources/logger/file/error-appender.xml
backend/src/main/resources/logger/file/info-appender.xml
backend/src/main/resources/logger/file/warn-appender.xml

close #763
1. 로그백의 설정을 SizeAndTimeBased -> TimeBased로 변경합니다.
1. 이슈에 변경 이유 작성해놓았으니 참고 부탁드립니다~

로그백 롤링 파일 정책 변경

---

frontend/src/components/ContactUs/ContactUs.style.ts
frontend/src/components/ContactUs/ContactUs.tsx
frontend/src/components/Footer/Footer.tsx
frontend/src/components/Header/Header.style.ts
frontend/src/components/Header/Header.tsx
frontend/src/components/Input/Input.tsx
frontend/src/components/Modal/Modal.tsx
frontend/src/components/Textarea/Textarea.stories.tsx
frontend/src/components/Textarea/Textarea.style.ts
frontend/src/components/Textarea/Textarea.tsx
frontend/src/components/index.ts
frontend/src/hooks/useInput.ts
frontend/src/service/validates.ts
frontend/src/utils/index.ts
frontend/src/utils/reactChildrenHelpers.ts

- #751 
- 페이지가 아닌 모달로 구현한 이유 : 모든 페이지에서 쉽게 접근하고, 쉽게 보낼 수 있도록 하는게 중요하다고 생각했기 때문입니다. 새템플릿을 작성하고 있는 와중에 페이지 이동이 되면 불편할 것이라고 판단되어 모달로 구현하였습니다.
- 사용의 편의성을 위해 `Input` 컴포넌트와 유사한 구조로 구현하였습니다.
- `minRow` 와 `maxRow`를 받아  최소 `minRow`만큼 보여주고,  `maxRow`가 넘어갈 경우 스크롤 처리가 됩니다.
- 본 컴포넌트가 바로 문의하기 모달입니다.
- 현재 `Header` 와 `Footer`에 달아주었습니다.
- 별도의 훅으로 로직을 분리하지 않고, 구글시트와 연동 등 모든 로직을 컴포넌트 내부에 함께 두었습니다. 그 이유는 로직이 단순하고, 변경될 여지가 적으며, 재사용될 가능성이 현저히 낮기 때문입니다.
- 현재 사용자가 위치한 라우터에 따라 Header 에서 어디에 있는지 알 수 있도록 스타일을 변경해주었습니다.

문의하기 모달 생성

---

backend/src/test/java/codezap/global/MockMvcTest.java
backend/src/test/java/codezap/tag/controller/TagControllerTest.java

close #767
1. 태그 컨트롤러 테스트를 추가했습니다.
+ `GET /tags` API

TagControllerTest 작성

---

backend/src/main/resources/logger/file/error-appender.xml
backend/src/main/resources/logger/file/info-appender.xml
backend/src/main/resources/logger/file/warn-appender.xml

close #790 
로그백 설정이 변경됩니다. 
```xml
// info-appender.xml
<fileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}/info/info%i.log</fileNamePattern>
// warn-appender.xml
<fileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}/warn/warn%i.log</fileNamePattern>
// error-appender.xml
<fileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}/error/error%i.log</fileNamePattern>
```
```xml
// info-appender.xml
<fileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}/info.log</fileNamePattern>
// warn-appender.xml
<fileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}/warn.log</fileNamePattern>
// error-appender.xml
<fileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}/error.log</fileNamePattern>
```
TimeBasedRollingPolicy에서는 파일별 용량을 고려해 rolling할 수 없는 것으로 보입니다. 
대신 압축은 지원해요. 
> TimeBasedRollingPolicy supports automatic file compression. …

로그백 설정 오류로 서버가 실행되지 않는 버그 픽스

---

backend/src/main/resources/logger/file/error-appender.xml
backend/src/main/resources/logger/file/info-appender.xml
backend/src/main/resources/logger/file/warn-appender.xml

#790 
#791 
로그백 설정이 변경됩니다. 
```xml
<file>${LOG_FILE_PATH}/${DATE_FORMAT}/error.log</file>
<fileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}/error.log</fileNamePattern>
```
```xml
<file>${LOG_FILE_PATH}/error.log</file>
<fileNamePattern>${LOG_FILE_PATH}/%d{yyyy-MM-dd}/error.log</fileNamePattern>
```
TimeBasedRollingPolicy에서는 파일별 용량을 고려해 rolling할 수 없기 때문에, 현재 실행중인 서버의 로그와 롤링된 파일의 이름이 동일합니다. 
로그 경로와 이름이 동일하기 때문에 설정이 충돌되어 실행되지 않아요 😭
그래서 경로를 다르게 변경했습니다 😭
개발서버에서 실행 되는 거 확인했어요!!
ASAP

로그백 설정 오류로 서버가 실행되지 않는 버그 픽스 (re)

---

backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
backend/src/main/java/codezap/likes/repository/LikesRepository.java
backend/src/main/java/codezap/likes/service/LikesService.java
backend/src/main/java/codezap/tag/repository/TemplateTagJpaRepository.java
backend/src/main/java/codezap/tag/repository/TemplateTagRepository.java
backend/src/main/java/codezap/tag/service/TagService.java
backend/src/main/java/codezap/template/controller/TemplateController.java
backend/src/main/java/codezap/template/repository/SourceCodeJpaRepository.java
backend/src/main/java/codezap/template/repository/SourceCodeRepository.java
backend/src/main/java/codezap/template/repository/ThumbnailJpaRepository.java
backend/src/main/java/codezap/template/repository/ThumbnailRepository.java
backend/src/main/java/codezap/template/service/SourceCodeService.java
backend/src/main/java/codezap/template/service/ThumbnailService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/test/java/codezap/likes/repository/FakeLikeRepository.java
backend/src/test/java/codezap/likes/repository/LikesJpaRepositoryTest.java
backend/src/test/java/codezap/template/repository/FakeSourceCodeRepository.java
backend/src/test/java/codezap/template/repository/FakeTemplateTagRepository.java
backend/src/test/java/codezap/template/repository/FakeThumbnailRepository.java
backend/src/test/java/codezap/template/repository/SourceCodeRepositoryTest.java
backend/src/test/java/codezap/template/repository/ThumbnailRepositoryTest.java
backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java

#645
> [관련 PR 코멘트](https://github.com/woowacourse-teams/2024-code-zap/pull/737#discussion_r1788539392)
- 메서드명 수정
- `deleteByMemberAndIds(Member member, List ids)` -> `deleteAllByMemberAndTemplateIds(Member member, List templateIds)`
- 서비스 단에 모든 `deleteByTemplateIds(List templateIds)` -> `deleteAllByTemplateIds(List templateIds)`
- 레포지토리 단에 모든 `deleteByTemplateIds(List ids)` -> `deleteAllByTemplateIds(List templateIds)`
- `@param` 추가
- 코드 일관성을 위해 모든 JPQL에 `@param`을 추가했습니다 !
가끔 설정이 안되있는 경우 자동으로 param 설정이 안될 때가 있음을 방지하기 위해, 앞으로 JPQL 사용 시  `@param`을 필수로 하면 좋을 것 같아요. 
10/17 10:00 (오전)

delete 메서드명 명확하게 변경

---

frontend/package-lock.json
frontend/playwright/tests/search.spec.ts
frontend/playwright/tests/templates.spec.ts
frontend/src/api/templates.ts
frontend/src/queries/templates/useTemplateExploreQuery.ts
frontend/src/queries/templates/useTemplateQuery.ts

- #745 
> - api 변경에 따른 /login 엔드포인트 제거

api 변경에 따른 /login 엔드포인트 제거

---

.github/workflows/backend_cd.yml
.gitmodules
backend/build.gradle
backend/src/main/java/codezap/global/logger/RequestResponseLogger.java
backend/src/main/resources/application-actuator.yml
backend/src/main/resources/application-cors.yml
backend/src/main/resources/application-db.yml
backend/src/main/resources/application-swagger.yml
backend/src/main/resources/application.yml

close #744
- 이제부터 git submodule을 사용합니다. 
- [Private 저장소](https://github.com/codezap2024/2024-code-zap-private)에 원격 서버(AWS EC2) 구성을 저장하고 관리합니다. 
- 변경된 내역을 코드잽 저장소의 CD 파이프라인을 사용해 반영합니다. 
- 서버에 SSH로 접속해서 설정을 변경하는 대신, Github Actions로 스프링 코드와 함께 배포합니다. 
https://github.com/woowacourse-teams/2024-code-zap/issues/744#issuecomment-2395329141
https://github.com/woowacourse-teams/2024-code-zap/issues/744#issuecomment-2418533869
https://github.com/woowacourse-teams/2024-code-zap/issues/744#issuecomment-2418540038
https://github.com/woowacourse-teams/2024-code-zap/issues/744#issuecomment-2418543211
10.18(금) 20:00

Git Submodule을 사용하여 AWS EC2에 위치한 설정을 관리하도록 변경

---

frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
frontend/src/components/TagInput/TagInput.tsx
frontend/src/hooks/template/useTag.ts
frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
frontend/src/utils/getLanguageByFileName.ts
frontend/src/utils/index.ts

- #803 
- 확장자 기반으로 언어 태그 자동 생성 기능 추가되었습니다.
- `jsx`, `tsx`의 경우 'react'로 생성됩니다.
- 파일 확장자를 바꾼다고 해서 기존 태그들이 삭제되지는 않습니다. 예를들어 파일 이름이 `example.js` 라고 적으면 `javascript` 태그가 추가됩니다. 이때 동일한 파일명을 `example.java`로 바꾸게 되면 `java`가 추가적으로 생성됩니다. 이전에 생성된 `javascript` 태그를 삭제할 순 없습니다. 유저가 추가한 태그 와 이전에 추가된 값들을 구분할 수 없기 때문에 임의로 삭제하기 힘들기 때문입니다.
10/18

확장자 기반으로 언어 태그 자동 생성 기능 추가

---

backend/src/test/java/codezap/auth/service/AuthServiceTest.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java
backend/src/test/java/codezap/global/ServiceTest.java
backend/src/test/java/codezap/likes/service/LikesServiceTest.java
backend/src/test/java/codezap/member/service/MemberServiceTest.java
backend/src/test/java/codezap/tag/service/TagServiceTest.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java
backend/src/test/java/codezap/template/service/ThumbnailServiceTest.java
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java

close #650
> 저번 ServiceTest 작성 시 나눠서 작업하느라 ServiceTest를 상속받은 것도 있고 아닌 것도 있어서 관리하기 편하도록 통일 시켰습니다~!
10/18 18:00

모든 ServiceTest가 Base 클래스를 상속받도록 통일

---

.github/workflows/pr_notification.yml

close #802 
> github action에서 PR 생성 시 리뷰하라고 슬랙 알람을 보내고 있습니다~
zap이 달린 경우 슬랙 메시지를 조금 수정했어요 참고바람
10/18 18:00

ZAP PR 생성 시 리뷰 메시지 변경

---

backend/src/main/java/codezap/template/repository/TemplateSpecification.java
backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java

close #829
> 태그 검색 조건을 and에서 or로 변경하였습니다.
10/21 23:59

태그 검색 조건 or로 변경

---

backend/src/main/java/codezap/auth/service/AuthService.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/main/java/codezap/likes/service/LikesService.java
backend/src/main/java/codezap/member/service/MemberService.java
backend/src/main/java/codezap/tag/service/TagService.java
backend/src/main/java/codezap/template/service/SourceCodeService.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/main/java/codezap/template/service/ThumbnailService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/main/resources/application-db.yml

close #830
> 모든 서비스 로직에 @Transactional을 적용했습니다.
- #830 에서 적어놓은 것은 `@Transactional`을 모든 서비스 클래스에 기본으로 설정해놓고, `readOnly`가 필요한 메소드만 별도로 `@Transactional(readOnly = true)` 를 붙여주는 것이었습니다.
- 하지만 이렇게 할 경우 다른 개발자가 합류했다고 했을 때, 어떤 트랜잭션 옵션이 붙어있는지 확인하기 힘들 수도 있겠다는 생각이 들었습니다.
- 또한, 이슈에 적은 방법을 제안한 이유는 write인데 readOnly를 붙여서 발생하는 휴먼에러를 방지하기 위함인데, 그렇게 하지 않아도 어차피 발생할 수 있는 오류라고 생각됩니다. 
- 따라서 모든 메소드에 명시적으로 작성하는 방법을 제안하는데 다들 의견이 어떠신가요??
10/21 23:59

서비스 트랜잭션 적용

---

frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx

- close #843 
> 기존 템플릿 수정 페이지에만 적용되어있던 템플릿 순서 정렬 로직을 업로드 페이지에서도 적용
ASAP - 버그 픽스라 빠르게 부탁드립니다.

새 템플릿 업로드 시, 템플릿 순서 정렬

---

frontend/src/components/ContactUs/ContactUs.style.ts
frontend/src/components/ContactUs/ContactUs.tsx
frontend/src/components/Modal/Modal.style.ts
frontend/src/pages/LandingPage/LandingPage.tsx
frontend/src/pages/MyTemplatesPage/components/ConfirmDeleteModal/ConfirmDeleteModal.tsx
frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx

- #826 
- 문의하기 모달에서 응답이 올 경우 무조건 성공으로 간주하고, 성공 토스트 띄우기
- 수정시 기본으로 현재 visibility 설정되도록 변경
- 선택 삭제 확인 모달 메세지 줄 바꿈 되도록 변경
- 랜딩페이지 오타 수정
- 현재 no-cors 로 요청을 보내고 있기 때문에 만에하나 요청이 실패할 경우에 저희가 할 수 있는 일이 없습니다.
- 추후 클라이언트는 백엔드로 요청을 보내고, 백엔드에서 Google apps 에 보내는 방향으로 마이그레이션 해야할 것 같습니다.
10/21 18:00

문의하기 모달 버그 수정 및 템플릿 수정시 visibility 기본값 설정

---

frontend/package-lock.json
frontend/package.json
frontend/src/components/Header/Header.tsx
frontend/src/components/PagingButtons/PagingButtons.tsx
frontend/src/components/SourceCodeViewer/SourceCodeViewer.tsx
frontend/src/index.tsx
frontend/src/pages/LandingPage/LandingPage.tsx
frontend/src/pages/LoginPage/LoginPage.tsx
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/pages/SignupPage/SignupPage.tsx
frontend/src/pages/TemplateEditPage/TemplateEditPage.tsx
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
frontend/src/pages/TemplatePage/TemplatePage.tsx
frontend/src/pages/TemplateUploadPage/TemplateUploadPage.tsx
frontend/src/service/amplitude/AmplitudeInitializer.tsx
frontend/src/service/amplitude/getBrowser.ts
frontend/src/service/amplitude/index.ts
frontend/src/service/amplitude/track.ts
frontend/src/service/amplitude/usePageViewed.ts
frontend/src/service/amplitude/useTrackPageViewed.ts

- #259 
- Amplitude를 설치 및 초기 설정을 하고 track 메서드를 커스텀 했습니다.
- 핵심 기능 중 하나인 템플릿 업로드 유저 플로우를 트래킹하는 작업을 만들어보았습니다.
1. Header의 새 템플릿 버튼에 클릭 이벤트 track
2. 템플릿 업로드 페이지가 보였을 때, 이벤트 track
3. 템플릿 저장 버튼 클릭 이벤트 track
- 추가로 해당 이벤트에 title, 소스코드 갯수, visibility를 추가 정보로 제공했습니다.
위의 설정으로 제가 생각하고 있는 정보는 다음과 같습니다.
- 템플릿 업로드 페이지에 들어온 순간 ~ 저장까지의 걸리는 시간
- 업로드 페이지에 들어왔지만 저장 버튼 안 누름 -> 유저 이탈
- 한 템플릿으로 업로드하는 소스 코드 갯수
- 템플릿의 visibility에 대한 갯수 데이터
- 관련 환경변수가 추가되었습니다. 로컬 실행에 필요하다면 따로 공유 드릴게요. codepipeline에도 추가해야합니다.
- Amplitude 계정은 codezap2024 구글 계정입니다.
1. Amplitude 선택 이유는 노션으로 공유하겠습니다.
2. Amplitude 사용법은 저도 배우면서 한 지라, 공식 문서 및 해당 링크를 참고해주세요.
https://amplitude.com/docs/sdks/analytics/browser/browser-sdk-2
10/22 11:59
다만 최대한 빨리 해당 기능을 운영서버에 띄우는게 좋을 것 같아 `zap` 태그 달아놓겠습니다.

Amplitude 초기 설정 및 핵심 기능(업로드) 트래킹

---

backend/src/main/java/codezap/template/controller/SpringDocTemplateController.java
backend/src/main/java/codezap/template/domain/Template.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/main/java/codezap/template/service/facade/TemplateOwnershipChecker.java
backend/src/test/java/codezap/template/domain/TemplateTest.java
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java

#739
- 단건 조회 시 다른 사람의 비공개 템플릿 조회일 경우 예외 발생
- ErrorCode.FORBIDDEN_ACCESS, "해당 템플릿은 비공개 템플릿입니다."
- DB에서 템플릿 기본 값을 PUBLIC으로 설정
10/23 10:00
해당 PR은 내일 릴리즈 전에 올라가야할 것 같습니다~ 빠른 리뷰 부탁드려요 !

상세 조회에서 다른 사람의 비공개 템플릿 확인 시 예외 처리

---

backend/src/main/resources/db/migration/V8__replace_ft_parser.sql
backend/src/test/java/codezap/fixture/TemplateFixture.java
backend/src/test/java/codezap/global/DatabaseCleaner.java
backend/src/test/java/codezap/template/repository/TemplateSearchJpaRepositoryTest.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java

close #719 
한글 키워드 검색 시에 템플릿이 "안녕하세요" 이고 키워드가 "안녕하"였다면 검색이 불가능했습니다.
검색 인덱스에 n-gram parser를 적용하여 부분 일치 검색이 가능하도록 변경합니다.
source_code의 filename, content는 영어이기 때문에 변경하지 않습니다.
NGram은 주어진 텍스트를 N개의 연속된 단위로 쪼개는 방법입니다.
한글은 조사/어미 변화가 많고 형태소 분석이 복잡하기 때문에 영어처럼 기본 파서를 활용하면 위 사례처럼 검색이 불가능합니다.
`검색하다 → 검색해요, 검색합니다, 검색했어요, 검색하니까` ➡️ 단순 정확 매칭으로는 "검색하다"를 찾을 때 위의 변형들을 찾지 못함
보통 필드가 중국어, 일본어, 한국어(CJK)라면 ngram을 사용해서 처리한다고 하네용 참고!
00/00 00:00

full text index 한글 필드에 대해 n-gram parser 적용

---

frontend/src/components/AuthorInfo/AuthorInfo.style.ts
frontend/src/components/AuthorInfo/AuthorInfo.tsx
frontend/src/components/TemplateCard/TemplateCard.style.ts
frontend/src/components/TemplateCard/TemplateCard.tsx
frontend/src/pages/MyTemplatesPage/components/TemplateGrid/TemplateGrid.tsx
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
frontend/src/pages/TemplatePage/TemplatePage.style.ts
frontend/src/pages/TemplatePage/TemplatePage.tsx

- #642 
1. 템플릿 카드의 클릭 가능 영역이 변경되었습니다.
- 유저 이름 클릭 시, 해당 유저의 템플릿 페이지로 이동
- 템플릿 제목, 설명, 소스코드만 클릭 가능하도록 변경
2. 유저 이름 hover 스타일이 변경되었습니다.
3. AuthorInfo 컴포넌트를 분리하였습니다.
10/24 23:00

템플릿 카드의 클릭 가능 영역 변경 및 유저 이름 클릭 시 유저 페이지로 이동

---

frontend/src/components/AuthorInfo/AuthorInfo.style.ts
frontend/src/components/TemplateCard/TemplateCard.style.ts
frontend/src/components/TemplateCard/TemplateCard.tsx

- #642 
1. 사용자 이름 ellipsis 처리
2. 모바일 환경일 때 템플릿 카드의 시간 숨김
- 사용자 이름이 너무 길때, 이름을 너무 줄일 수는 없어서 시간을 숨기도록 했습니다.
zappp

사용자 이름 ellipsis 처리 및 모바일 환경일 때 템플릿 카드의 시간 숨김

---

frontend/src/components/AuthorInfo/AuthorInfo.style.ts
frontend/src/components/SourceCode/SourceCode.tsx

- #642 
1. 모바일 환경의 SourceCode 폰트 사이즈 변경합니다.
zapppp

모바일 환경의 SourceCode 폰트 사이즈 변경

---

frontend/src/components/SelectList/SelectList.style.ts
frontend/src/components/SelectList/SelectList.tsx
frontend/src/components/SourceCode/SourceCode.tsx
frontend/src/components/SourceCodeEditor/SourceCodeEditor.tsx
frontend/src/components/SourceCodeViewer/SourceCodeViewer.style.ts
frontend/src/components/Toast/Toast.style.ts
frontend/src/pages/TemplatePage/TemplatePage.tsx
frontend/src/routes/router.tsx

- #890 
- RouteGuard 제거
- 참고로 존재하지 않는 멤버 아이디로 접근할 시 아래와 같이 404 페이지가 보입니다.
-  노드모듈을 다 삭제하고 다시 깔아서인지 import 에러가 나는 부분이 있었습니다.
- useTheme 사용하여 theme을 불러온 부분 => theme 직접 import 해와서 해결
- SourceCode에서 ViewUpdate import => @uiw/react-codemirror 에서 불러오도록 하여 해결
10/31
ZZZZZAP!! 오늘 안에 main 까지 올려서 재배포 하면 좋을 것 같아요!

로그인하지 않아도 사용자 페이지 접근 가능하도록 RouteGuard 제거

---

backend/src/main/java/codezap/likes/service/LikesService.java
backend/src/main/java/codezap/template/domain/Template.java
backend/src/main/resources/db/migration/V9__like_column_denormalization.sql
backend/src/test/java/codezap/likes/service/LikesServiceTest.java
backend/src/test/java/codezap/template/domain/TemplateTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java

close #741
> Template 테이블에 존재하던 좋아요 컬럼을 반정규화하였습니다.
> 동시성 문제가 발생할 가능성이 높으니 해당 PR 머지 후 문제를 추가 검토하겠습니다.
11/06 13:00

좋아요 컬럼 반정규화

---

backend/src/main/java/codezap/global/pagination/FixedPage.java
backend/src/main/java/codezap/global/pagination/FixedPageCounter.java
backend/src/main/java/codezap/likes/repository/LikesJpaRepository.java
backend/src/main/java/codezap/likes/repository/LikesRepository.java
backend/src/main/java/codezap/likes/service/LikesService.java
backend/src/main/java/codezap/template/dto/response/FindAllTemplatesResponse.java
backend/src/main/java/codezap/template/repository/TemplateQueryDSLRepository.java
backend/src/main/java/codezap/template/repository/TemplateRepository.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/test/java/codezap/global/pagination/FixedPageCounterTest.java
backend/src/test/java/codezap/global/repository/RepositoryTest.java
backend/src/test/java/codezap/likes/repository/LikesRepositoryTest.java
backend/src/test/java/codezap/likes/service/LikesServiceTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/repository/TemplateRepositoryTest.java
backend/src/test/java/codezap/template/repository/TemplateSearchRepositoryTest.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java
backend/src/test/resources/search.sql

close #899
1. 목록 조회에서 페이지네이션이 들어갈 경우, Page 반환타입은 전체 페이지와 요소 갯수를 반환합니다.
그 과정에서 전체 로우를 풀스캔하기 때문에 비효율적입니다.
(조회 조건에 해당되는 컬럼이 100만건이라면 100만 로우를 전체 카운팅)
현재 페이지네이션 바가 5개까지 나타나기 때문에 전체 로우를 카운팅하지 않고 현재 페이지 포함 5개 페이지까지가 있는지 반환합니다.
```
예) 
조건에 맞는 전체 페이지가 10개인 경우: nextPages는 5개 
조건에 맞는 전체 페이지가 1개인 경우: nextPages는 1개 
```
2. `내가 좋아요한 템플릿 목록 조회 API`에서 동일한 페이지네이션 바가 사용되기 때문에 `템플릿 목록 조회 API`와 동일하게 5개까지만 반환하는 처리를 하였습니다.
그 과정에서 `내가 좋아요한 "템플릿" 목록 조회` 레포지토리 메서드를 template 패키지로 이동하였습니다. (이전 담당자와 상의 완, 참고바람~~)
> 관련 논의 디스커션 참고: [템플릿 목록 응답의 전체 템플릿 수의 필요성에 대해 이야기해봐요](https://github.com/woowacourse-teams/2024-code-zap/discussions/778)
+) Repository 단 테스트 시에 관련 Config 들을 Import해야하는데 @TemplateSearchRepositoryTest와 @RepositoryTest의 @Import가 중복으로 수정되네욥ㅠ 이번 PR에서 변경사항이 많이 잡힐 것 같아 따로 PR 올릴게욥
11/11 18:00

페이지네이션 처리 시 최대 다음 페이지 수를 5개로 제한

---

frontend/src/components/PagingButtons/PagingButtons.stories.tsx
frontend/src/components/PagingButtons/PagingButtons.tsx
frontend/src/mocks/handlers.ts
frontend/src/pages/MyLikedTemplatePage/MyLikedTemplatePage.tsx
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx
frontend/src/service/amplitude/track.ts
frontend/src/types/api.ts

- #899 
- 검색 성능을 올리기 위해 백엔드와 함께 api를 변경하였습니다. 이에 따라 totalPages와 totalElements 를 제거하고, paginationSizes를 적용하였습니다. (paginationSizes 는 **현재 페이지를 포함**하여 다음에 몇 페이지까지 있는지를 반환하는 **`number`** 입니다.)
- `<<`, `<`, `>`, `>>` 버튼 모두 삭제하였습니다.
- (관련 백엔드 api 변경 PR) #902  
- 아래와 같이 api 변경될 예정이라고 합니다.
- (11/13 업데이트) paginationSizes로 변수명이 변경되었습니다. 
11/14 12:30

totalPages => paginationSizes 로 변경

---

frontend/src/hooks/template/index.ts
frontend/src/hooks/template/useSearchKeyword.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.style.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/pages/MyTemplatesPage/hooks/useFilteredTemplateList.ts
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.style.ts
frontend/src/pages/TemplateExplorePage/TemplateExplorePage.tsx

- #899 
- 내템플릿, 구경가기 페이지에서 템플릿 검색시 엔터를 눌러야 검색되도록 변경하였습니다.
- inputKeyword은 검색창에 입력되어있는 상태, searchedKeyword는 실제 검색된 상태(queryParam에 있는 keyword)를 의미합니다.
11/15

템플릿 검색시 엔터를 눌러야 검색되도록 변경

---

backend/src/main/java/codezap/tag/service/TagService.java
backend/src/test/java/codezap/tag/service/TagServiceTest.java

close #921
1. 기존 로직은 태그 저장 시에 기존에 존재하는 태그만 체크합니다. 새로 저장하려는 태그에 중복이 있는 경우 모두 저장됩니다. 따라서 태그 이름에 제거 후 저장하도록 변경하였습니다.
2. 태그 저장 메서드가 복잡하여 메서드를 추출하였습니다. 
1. TemplateTagService와 TagService의 분리가 필요해보입니다.
11/17 18:00

태그가 중복 저장되는 버그 해결

---

frontend/src/components/Layout/Layout.tsx
frontend/src/routes/router.tsx

- #439 
- `routes.ts`에 중복 적용되어있던 `CustomSuspense`와 `ErrorBoundary`를 제거하고 `Layout`에 적용하였습니다.
- 컴포넌트 명을 각각 `GlobalSuspense`와 `GlobalErrorBoundary`로 변경하였습니다.
11/29 20:00

index의 중복 적용된 Suspense, ErrorBoundary 제거

---

backend/src/main/java/codezap/global/swagger/SpringDocConfiguration.java
backend/src/main/resources/application-swagger.yml

#858
운영 환경에서 API 문서 접근 및 테스트가 불가능하도록 변경해요. 
개발 및 운영 환경의 환경 변수를 추가합니다. 
```
SWAGGER_ENABLED=true
SWAGGER_ENABLED=false
```
12/05 13:01

운영 환경에서 Swagger 문서 및 API 차단

---

backend/src/main/java/codezap/global/logger/MDCFilter.java
backend/src/main/java/codezap/global/logger/MethodExecutionTimeAspect.java
backend/src/main/resources/logger/logback-spring-prod.xml

close #952
직전 회의 때 논의했던 내용으로 사용자의 로그 추적을 쉽게 하기 위해 로그 전략을 수정했습니다.
> 회의에 참여하지 못하셨던 분은 이슈 참고하시면 좋을 것 같슴다!
- 운영 환경 로깅에서 codezap 로깅 레벨도 info로 낮춤
- MethodExecutionTimeAspect를 debug로 낮츰
- 상수 하나에 static 키워드가 빠져있어 수정
12/07 22:00

운영 환경, 메서드 로그 전략 변경

---

backend/src/main/java/codezap/template/repository/strategy/FullTextSearchSearchStrategy.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java

close #962 
- 검색 키워드 앞 또는 뒤에 특수문자가 붙으면 500 에러가 발생합니다.
- ex) '+test', '-리스트', '이름-' 등등
- 키워드에 특수 문자가 있는 경우, 특수 문자를 제거하고 검색하도록 변경하였습니다.
> 토요일 전에 운영 환경에 배포되어야 할 것 같아서 최대한 빠른 리뷰 부탁드립니다.
12/13 16:00

검색시 발생하는 500 에러 해결

---

frontend/src/index.tsx
frontend/src/mocks/handlers/category.ts
frontend/src/pages/MyTemplatesPage/MyTemplatePage.tsx
frontend/src/pages/MyTemplatesPage/components/TemplateListSection/TemplateListSection.tsx

#973 
기존 타인의 템플릿에서 카테고리들 중 템플릿이 없으면 업로드 버튼이 보이고 있었습니다. 
기존 코드에서 이미 `isMine` 이라는 조건으로 edit 모드 처리를 하고 있어서 해당 조건을 사용해서 처리했습니다. 
추가적으로 모킹 수정하고 반영되지 못한 수정사항이나 sort-option 등이 몇개 있어서 같이 처리해서 올렸습니다~ 
고민 중에 있는 부분은 `MyTemplatePage` 이라는 워딩 부분인데요,,~! 
사실상 url 로 맴버 템플릿이고 본인 템플릿과 더불어 다른 사람의 템플릿을 모아보기도 가능한 기능이라 `MemberTemplatePage` 로 변경하는 것에 대해서 어떻게 생각하시는지 궁금합니다,,~~ 
폴더 명도 `MyTemplatePage` 이다보니 diff 가 많이 생길거 같아서요! 
더불어 엠플리튜드 트래킹도 `[Viewed] 내 템플릿 페이지` 로 찍히고 있어서 제가 마위의 템플릿들을 구경해도 제 페이지를 보고 있는 걸로 찍힐거 같아서 수정이 필요할거 같습니다! 
12/20 12:00

타인의 템플릿 페이지에서 노출된 업로드 버튼 오류 수정

---

frontend/package.json
frontend/src/index.tsx
frontend/src/mocks/handlers/authentication.ts
frontend/src/mocks/handlers/like.ts
frontend/src/mocks/handlers/template.ts
frontend/src/utils/mockResponse.ts
frontend/webpack.dev.js

#975 
**1. msw 핸들러 추가 및 보수 진행**
- mockResponse 보수 
: 기존에 작업한 mockResponse 로 로그아웃을 진행할 때 500이 뜨는 버그가 있었습니다. 찾아보니 204를 보내면서 바디를 함께 주고 있어서 조건식에 204일때 처리를 따로 진행했습니다. 
- 좋아요한 템플릿 리스트 보는 핸들러 추가 
: 의도한건지 모르겠지만,, 좋아요한 템플릿 리스트 보는 핸들러가 없어서 짜봤습니다. 자꾸 들어가면 없어서 404가 뜨길래 거슬려서,, 
- 파일 업로드 이후 Location 추가 
: 템플릿 업로드 이후 prod 환경에서는 백엔드에서 전달 받은 location을 사용하여 페이지 이동을 하는데 모킹에서도 비슷하게 구현하고 싶어서 `location` 을 걸어주었습니다. 그런데 아무래도 아직 어설픈 모킹이다보니 새로 생성된 페이지가 아니라 일단 1번으로 이동되게했습니다. 
이후에 모킹쪽을 조금 더 자세히 보고 유지보수할 수 있지 않을까... 
**2. msw 자동 실행 스크립트 추가** 
제 사수이자 대리이자 부장이자 CTO 이신 마위께서 자꾸 일거리를 주셔서 이 야밤에 작업을 했습니다.. 
이제 msw 실행 주석을 지울 필요 없이 실행 명령어에서 `npm run msw` 를 실행하시면 자동으로 msw 환경으로 사용하실 수 있습니다. 
아 env 업데이트가 필요합니다. 자세한 사항은 카톡으로,,,
다만 의문인건 원래 dev로 실행하면 CORS 나는게 맞는건지,,,? 
12/20 12:00

msw 핸들러 추가 및 msw 실행 스크립트 추가

---

backend/build.gradle
backend/src/main/java/codezap/global/retry/RetryConfiguration.java
backend/src/main/java/codezap/tag/domain/Tag.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/main/resources/db/migration/V10__add_constraint_unique_tag.sql
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java

close #960 
1. 유니크 제약 조건
2. MySQL INSERT IGNORE
3. synchronized 키워드
위와 같았어요. 각 이유에 대해 우려되는 점들은 이슈에 작성해놓았습니다!
결론적으로는 유니크 제약 조건과 재시도로 처리하는 게 현재 상황에서 적절하다고 판단했어요!
따라서 재시도를 처리해주는 spring retry 의존성을 추가했습니다.
JPA에서 제공하는 unique 제약 조건은 대소문자를 구분하지 않아요.
때문에 기존 테스트 코드 중 "대소문자 구분하여 조회하는지"에 대한 테스트가 실패했어요.
우리의 정책은 태그의 대소문자를 구분하기 때문에 columnDefinition 옵션에 제약을 추가했으니 참고 부탁드립니다!
문제 상황을 재연하기 위한 테스트에서 ServiceTest에 @Transactional 어노테이션으로 인해 재연이 불가능해요.
@Disable 처리를 해놓았으니 문제 상황을 확인하고 싶으신 분들은 참고 부탁해요!
12/20 13:00

태그 동시 생성 시 중복 문제 해결

---

frontend/src/api/contact.ts
frontend/src/components/ContactUs/ContactUs.tsx
frontend/src/mocks/handlers/contact.ts
frontend/src/routes/endPoints.ts

- #851 
- 문의하기를 서버 api로 변경하였습니다.
- 일단 문의하기 본문에서 사용되는 최소/최대 글자수는 상수로 해당 파일에 위치시켰습니다. 별도의 constants 폴더로 분리하는 것보다 같은 파일에 있는 것이 더 유지보수가 용이하다고 생각했기 때문입니다. 혹시 다른 의견 있으시다면 답글달아주세요!!
- 논의 결과 최소 글자수는 10으로 변경하였습니다.
- ~~백엔드 api에 최소 글자수 제한이 아직 20자로 되어있어서 그대로 구현하였습니다. 이 부분은 다함께 논의 후 확정된 값으로 업데이트 하겠습니다. 따라서 그 전에 머지하지 말아주세요!!~~
- 이제 env 에서 GOOGLE_URL 지우셔도 됩니다!
~~12/23 23:59~~
12/24 23:59 (12/23일 업데이트)

문의하기 api 적용

---

backend/src/main/java/codezap/voc/controller/SpringDocVocController.java
backend/src/main/java/codezap/voc/controller/VocController.java
backend/src/main/java/codezap/voc/dto/VocRequest.java
backend/src/test/java/codezap/voc/controller/VocControllerTest.java
backend/src/test/java/codezap/voc/dto/VocRequestTest.java

#984
회의 내용에 따라 글자수 제한을 변경해요. 
명세에 따라 문의하기에 성공하면 상태코드 201을 응답하도록 고쳤어요. 
관리자 페이지가 생기면 구글 스프레드시트 대신 DB를 사용하는 방식으로 변경돼야 해요. 
12/24 21:00

문의하기 글자수 제한 20자 → 10자 변경 및 상태코드 200 → 201로 수정

---

backend/src/main/resources/application-was.yml
backend/src/main/resources/application.yml

#850 
아래의 설정을 추가해요. 
```yml
server:
compression:
enabled: true
```
`mime-types`, `min-response-size` 설정은 기본값을 사용하기 위해 커스텀하지 않았어요. 
기본값은 다음과 같아요. 
- `mime-types`: "text/html", "text/xml", "text/plain", "text/css", "text/javascript", "application/javascript", "application/json", "application/xml"
- `min-response-size`: 2KB
로컬에서 [운영 서버와 동일한 템플릿](https://www.code-zap.com/templates/1112) 하나를 생성하고 조회해봤어요. 
그리고 조회하면 다음과 같이 얼마나 압축됐는지 확인할 수 있어요. 
HTTP Body 용량을 67%나 줄였어요~!
계산식: $\left( \frac{9.93 - 3.26}{9.93} \right) \times 100 \approx 67.17\%$
본 설정을 적용하기 위해 `application-was.yml` 파일을 만들었어요. 
명명 근거는 다음과 같아요. 
- http compression은 WAS의 설정값이고, 우리가 tomcat을 netty, jetty 등 다른 서블릿 컨테이너로 변경하더라도 동일하게 적용되는 설정이에요. 
- 압축뿐 아니라 SSL, 스레드, 캐시, 세션 등의 설정도 할 수 있어요. 
- 모두 prefix가 `server.`으로 시작하고 모두 WAS의 기능이므로 확장 …

Tomcat HTTP gzip 압축 적용

---

backend/build.gradle

#955 
현재는 테스트 중에 실패하더라도 작업을 멈추지 않고 모든 테스트를 실행해요. 
아래 스크린캡처 이미지처럼, 시간이 오래 걸려요. 
아래의 gradle 옵션을 추가해요. 
```gradle
test {
failFast = true
}
```
Gradle test 작업 실행 중 테스트가 실패하면 작업을 멈춰요. 
이렇게하면 실패하는 CI의 작업 속도를 최대 99%(로컬 기준 48.973s → 358ms) 높일 수 있어요. 
계산식: $\left( \frac{48973 - 358}{48973} \right) \times 100 \approx 99.27\%$
12/24 22:30

Gradle test 작업에 fast-fail 옵션 추가

---

backend/src/main/java/codezap/category/repository/CategoryRepository.java
backend/src/main/java/codezap/category/service/CategoryService.java
backend/src/main/java/codezap/tag/service/TagService.java
backend/src/main/java/codezap/template/dto/request/CreateTemplateRequest.java
backend/src/main/java/codezap/template/dto/request/UpdateTemplateRequest.java
backend/src/main/java/codezap/template/repository/TemplateRepository.java
backend/src/main/java/codezap/template/service/SourceCodeService.java
backend/src/main/java/codezap/template/service/TemplateService.java
backend/src/main/java/codezap/template/service/ThumbnailService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java
backend/src/test/java/codezap/category/service/CategoryServiceTest.java
backend/src/test/java/codezap/tag/service/TagServiceTest.java
backend/src/test/java/codezap/template/controller/TemplateControllerTest.java
backend/src/test/java/codezap/template/repository/TemplateRepositoryTest.java
backend/src/test/java/codezap/template/service/SourceCodeServiceTest.java
backend/src/test/java/codezap/template/service/TemplateSearchServiceTest.java
backend/src/test/java/codezap/template/service/TemplateServiceTest.java
backend/src/test/java/codezap/template/service/facade/TemplateApplicationServiceTest.java

#948
- 사용하지 않는 메서드 제거 ( [COMMIT](https://github.com/woowacourse-teams/2024-code-zap/commit/e7ade222ad9d4921c145858114f2f158041a5075) )
- `@Disabled` 테스트 확인 후 수정 혹은 제거
- 수정 혹은 제거한 이유에 대해서는 이슈에 작성
- 소스코드 순서 검증 시 현재까지는 순서가 뒤죽박죽이면 예외 발생하는 방식을 변경
- 소스 코드 순서 검증 시 정렬하여 1부터 시작해 빠지는 값이 없다면 예외 발생하지 않게 수정
- 이유 : 이전 코드는 소스코드 업데이트 시 무조건 업데이트 소스코드가 생성 소스코드보다 앞선 순서여야하기 때문. 추후 소스코드 순서 변경을 고려해서 구현한 코드인 만큼 생성 소스코드가 수정 소스코드보다 클 수 있어야한다고 생각했습니다.
이해를 돕기 위해 코드를 가져오면 소스코드 순서를 확인하기 위해 사용했던 순서를 알아내는 코드는 다음과 같았습니다.
```java
public List<Integer> extractSourceCodesOrdinal() {
return Stream.concat(
updateSourceCodes.stream().map(UpdateSourceCodeRequest::ordinal),
createSourceCodes.stream().map(CreateSourceCodeRequest::ordinal)
)
.toList();
}
```
- @jminkkk 몰리가 태그 동시성 구현하면서 `@Disabled`로 만들었던 테스트를 …

@Disabled 된 테스트 검토 및 사용하지 않는 메서드 제거

---

backend/src/main/java/codezap/global/logger/RequestResponseLogger.java

close #989 
로그에 헤더가 너무 많아서 필요한 정보만 포함되도록 수정하였습니다.
실행중인 서버의 도커 컨테이너 정보가 response 로그에 포함되도록 수정하였습니다.
적혀있는 정보는 실행중인 도커의 `컨테이너 ID` 입니다.
> 무중단 배포를 도입하면서 현재 어떤 컨테이너가 실행중인지 파악하기 어렵다는 문제가 있었는데 이 로그를 통해 해결할 수 있을 것 같습니당.
> 현재 request 로그에는 origin, host, content-type을 추가하였고, response 로그에는 docker-hostname만 추가되도록 하였습니다.
더 추가되었으면 하는 헤더 정보가 있다면 얘기해주세용.
12/26 23:59

로그에 헤더 정보 수정 및 컨테이너 정보 추가

---

backend/src/main/java/codezap/tag/service/TagService.java
backend/src/main/java/codezap/template/service/facade/TemplateApplicationService.java

close #960
전체 템플릿 저장을 재시도하지 않고, 태그 생성 로직만 재시도 처리합니다.
전체를 재시도하는 것보다 더 효율적일 것 같아요.
01/03 13:00

태그 중복 생성 시 재시도 처리의 위치를 변경

---

backend/src/main/resources/application.yml

close #1008
default에 was, voc를 제거합니다.
회의 결과에 따라 앞으로 기본 yml인 로컬 yml에서는 내부에서 추가하여 사용합니다~!!
01/04 16:00

Default yml에서 was, voc 프로파일 제거

---

.github/workflows/frontend_cd.yml

- close #949 
- 프론트엔드 CD 스크립트 작성
clone 받은 개인 레포지토리 dev/fe 브랜치에서 테스트해보았고 잘 동작합니다.
이전 codePipeline에서 작업하던 CD를 github actions로 마이그레이션합니다.
현재 사용되고 있는 `AWS credentials`에는 S3와 cloudFront Full access 권한이 들어가 있습니다.
IAM 이름은 frontend-dev 입니다
(frontend-prod는 누가 만든건가요?)
각 환경 변수 넣어놓겠습니다.
`AWS_ACCESS_KEY_ID` : 엑세스 키 ID
`AWS_SECRET_ACCESS_KEY` : 엑세스 시크릿 키
`S3_BUCKET_NAME` :  버킷 이름
`CLOUDFRONT_DISTRIBUTION_ID_PROD` : cloudFront의 ID (프로덕션)
`CLOUDFRONT_DISTRIBUTION_ID_DEV` : cloudFront의 ID (개발서버)
01/07 23:59

프론트엔드 github actions CD 스크립트
